### ISSUE TITLE
snpe-量化问题

### ISSUE THREAD

**Issue by fengyanWang** [openppl-public/ppq#152]
请问是不是只要onnx转换成功，无论原始模型是caffe还是pytorch，都可以使用ppq正常进行量化？

**Comment by ZhangZhiPku** [comment]
是的，你只需要转出onnx，然后祈祷ppq没有bug

**Comment by ZhangZhiPku** [comment]
onnx得是opset11的，opset13我们正在努力支持...

**Comment by fengyanWang** [comment]
> onnx得是opset11的，opset13我们正在努力支持...

好，谢谢啦！
