### ISSUE TITLE
如何理解TargetPlatform?

### ISSUE THREAD

**Issue by PeiqinSun** [openppl-public/ppq#156]
首先, 很感谢你们开源为量化这方面做的贡献!
我先说一下我的理解: 这个变量应该是指我要部署的目标平台是什么? 按这个理解, 我可以理解CUDA / NXP / DSP / SNPE 等不同厂商的不同硬件, 甚至于后面接的数据类型: FP32 / FP16 / INT8 / INT4 都可以看成是不同的子硬件平台. 但我惟一感到困惑的是: 为什么要区分PPL_CUDA_INT8 和 TRT_INT8? 两者的应用目标不都是GPU吗? 那这里是隐含说一个是采用PPQ内嵌的量化算法然后直接生成engine模型给GPU部署, 另一个是采用TensorRT内自带量化算法?

**Comment by ZhangZhiPku** [comment]
首先我需要向你澄清，这个TargetPlatform决定的是"量化策略"。

你的理解是正确的，这个TargetPlatform描述了你要部署到那里，PPQ会根据这个变量选择量化策略。
你同时需要认识到部署的流程中，跟我们直接打交道的是Runtime，而非硬件。所以真实的情况是：
![未命名文件 (41)](https://user-images.githubusercontent.com/43309460/172327759-d3c3e319-5268-4bd3-90a0-d28f8f618472.png)
这个Targetplatfrom对应的是Runtime，而非硬件。

那么聪明的你可能想问，大家都是在同一个硬件上做量化，为什么可以有不同的量化策略？
对此我必须告诉你，它们不仅有所不同，而且差异很大...

为了更直观地说明这件事，你可以随便量化一个resnet18，分别以TargetPlatform.trt, TargetPlatform.pplcuda, TargetPlatform.metax设定量化策略，导出格式选择TargetPlatform.onnxruntime，观察它们之间的差异性。

**Comment by PeiqinSun** [comment]
非常感谢大佬的细心绘图描述, 一目了然很清晰. 回头我试试随便量化个resnet18.
