### ISSUE TITLE
conv pads cause forward error

### ISSUE THREAD

**Issue by wdian** [openppl-public/ppq#16]
model： 链接：https://pan.baidu.com/s/1IU1KdcSc2Ssxs3zjXY1IHQ 
提取码：8888

onnx model "auto_pad" is SAME_LOWER, The pads value corresponding to onnx is [1,1,0,0], format is  [x1_begin, x2_begin， x1_end, x2_end] .  but it cannot be mapped to the conv operator of pytorch.

**Comment by ZhangZhiPku** [comment]
Oops，如你所见我们使用pytorch的函数来运行onnx的计算图，但是显然pytorch并不打算支持[1,1,0,0]这样的特殊padding，因此我在ppq.utils.attributes.py文件的64行附近添加了相关的检查，你的模型如果具有形如[1,1,0,0]这样的padding，我应该会向你报告错误。

由于torch并不支持如此特殊的padding形状，解决这一问题需要我们手工书写cuda kernel，这个Feature我们预计在ppq后续的版本中慢慢添加。如果你了解cuda kernel的写法，你也可以在ppq/csrc中添加你的实现。

就目前而言，唯一能够让你网络正常运行的方法是将你的padding shape改成[1,1,1,1]，而后在padding后的结果result上执行
result=result[:-1, :-1]，即手工舍弃第一、二维的最后一排元素。你可以通过修改ppq.utils.attributes.py函数，禁用我的检查，并直接修改ppq.executor.op.torch.default.py中的Conv_forward函数来实现你所需的功能。

**Comment by Jzz24** [comment]
已经修复啦，是ppq代码计算auto_pads的bug

**Comment by Jzz24** [comment]
已修复；

**Comment by Jzz24** [comment]
已修复，是由于ppq.utils.attributes.py里面，当pad_needed为奇数时，pads计算出现问题。修改后你所提供的模型 ort_fp32和ppq_fp32可以完全对齐，并成功导出。
