### ISSUE TITLE
量化后模型，转换为 tensorrt int8 engine，inference 不对齐

### ISSUE THREAD

**Issue by FreemanHsu** [openppl-public/ppq#173]
Hello, 
我在尝试使用 PPQ 量化来得到 Tensorrt Int8 模型，发现模型比较大的时候，QDQ Onnx 模型转 TRT Int8 似乎存在性能问题 (无法对齐)，具体地，我尝试小模型如 mnist 时可以对齐 (1e-7量级误差)，稍大的模型如 resnet50 就存在较大的误差
我不确定是否我的操作存在问题，目前定位问题倾向于认为是 Tensorrt 转换过程引入了误差，所以我在 TensorRT repo 中提了 Issue，详见 https://github.com/NVIDIA/TensorRT/issues/2103
想请教一下是否遇到过类似的问题，谢谢！

**Comment by ZhangZhiPku** [comment]
oh，resnet50可是在我们的测试模型库之内...
让我来试一试...

**Comment by ZhangZhiPku** [comment]
我们的确知道trt读取qdq格式的文件经常会出问题，但是resnet50这种没啥特殊结构的一般还好
你要尽可能避免以下的事情：
1. group conv好像会出问题
2. 自定义算子的int8解析好像会出问题
3. index操作太多好像会出问题
4. 其他奇怪的问题

**Comment by FreemanHsu** [comment]
看起来是我的预期不太对，在 trt 8.x 之后，我看到支持 qdq 模型的 explicit int8 转换，先入为主地认为只是做简单的 onnx quantized model 到 trt int8 的参数迁移，觉得应该能看到 onnxruntime 和 trt 能够强对齐的
我用你的测试脚本跑了 resnet，Simulating Error:  0.0256%，看上去是在比较合理的抖动范围内的
不过在我自己的模型上(模型比较大，有 ConvTranspose，输出有 regression)，转到 TRT 之后误差就非常大，基本不能用的状态 T.T (TRT 8.4.1 也试过，也崩了)
顺便问一下，trt 7.x 不支持 qdq 的模型，如果希望 ppq 输出的 onnx 模型部署在 trt 7.x 的平台上，通常做法是什么样的呢? 利用输出的 ppq 或者 onnx 模型，统计各层输出的 minmax，再给到 trt 的 setDynamicRange 是一个可行的做法吗？

(你们回复得好快... 感谢

**Comment by ZhangZhiPku** [comment]
理论上可以，但是你要知道这玩意他里面图融合很复杂，特别是你这种里面乱七八糟的算子很多的网络...
这可能会导致一些错误和不可预期的情况...
随着量化领域的发展，trt, openvino 这些大平台逐渐都开始支持了读取qdq onnx的方式，并且结果也能与onnxruntime基本对齐，这是未来发展的趋势。trt在文档里也提到了比较提倡使用qdq模型直接给量化参数的模式，这种方式对于量化的控制更加透明。

你这个能转出来就不错了，很多复杂的模型trt直接识别不了，转换Int8会报错。既然已经转出来了，你可以用以下的方式debug：
  
      print('网络正量化中，根据你的量化配置，这将需要一段时间:')
      quantized = quantize_native_model(
          setting=QS,                     # setting 对象用来控制标准量化逻辑
          model=graph,
          calib_dataloader=dataloader,
          calib_steps=32,
          input_shape=NETWORK_INPUTSHAPE, # 如果你的网络只有一个输入，使用这个参数传参
          inputs=None,                    # 如果你的网络有多个输入，使用这个参数传参
          collate_fn=lambda x: x.to(EXECUTING_DEVICE),  # collate_fn 跟 torch dataloader 的 collate fn 是一样的，用于数据预处理，
                                                      # 你当然也可以用 torch dataloader 的那个，然后设置这个为 None
          platform=TARGET_PLATFORM,
          device=EXECUTING_DEVICE,
          do_quantize=True)
      
      formatter = GraphFormatter(quantized)
      formatter.truncate_on_var(quantized.variables['Your Variable Name'], mark_as_output=True)
      
      export_ppq_graph(quantized, ...)

GraphFormatter.truncate_on_var 将会从一个指定节点出发，将你的图进行截断，所有下游节点将被移除
你可以借助这个性质来判断到底是哪一个算子出的问题，进而找到合适的方法绕开他。

**Comment by songkq** [comment]
> @ZhangZhiPku 请问我这里导出模型报错是啥问题？
```
export_ppq_graph(
    graph=quantized, platform=TargetPlatform.TRT_INT8,
    graph_save_to=ONNX_OUTPUT_PATH,  config_save_to=TRT_QUANT_CFG_PATH)
```

```
Traceback (most recent call last):
  File "error_analyse.py", line 224, in <module>
    export_ppq_graph(
  File "/workspace/3rd_party/ppq/ppq/api/interface.py", line 590, in export_ppq_graph
    exporter.export(file_path=graph_save_to, config_path=config_save_to, graph=graph, **kwargs)
  File "/workspace/3rd_party/ppq/ppq/parser/tensorRT.py", line 322, in export
    self.export_quantization_config(config_path, graph)
  File "/workspace/3rd_party/ppq/ppq/parser/tensorRT.py", line 274, in export_quantization_config
    input_cfg = op.config.input_quantization_config[0]
AttributeError: 'Operation' object has no attribute 'config'
```

**Comment by zt706** [comment]
> 好的，我尝试一下，感谢！

我也遇到了这个问题 ， 通过对比QDQ+onnxruntime 和 导出后的 trt+int8 模型 结果。
**目前定位问题倾向于认为是 Tensorrt 转换过程引入了误差**

你的问题解决了吗

**Comment by FreemanHsu** [comment]
> > 好的，我尝试一下，感谢！
> 
> 我也遇到了这个问题 ， 通过对比QDQ+onnxruntime 和 导出后的 trt+int8 模型 结果。 **目前定位问题倾向于认为是 Tensorrt 转换过程引入了误差**
> 
> 你的问题解决了吗

Tensorrt 的模型转化过程，即便输入是带QDQ节点的模型，也不会保证转换出来的量化模型是强对齐的，内部仍然会做融合算子等操作 (未开源，所以不清楚细节)，导致有误差；目前来看不太有解
