### ISSUE TITLE
The time of model inference increases after doing int8 quantization

### ISSUE THREAD

**Issue by tuochi** [openppl-public/ppq#177]
my device is i7-8750H

Start Benchmark with openvino (Batchsize = 1)
Time span (FP32 MODE):  68.0568 sec
Time span (INT8 MODE):  85.6443 sec

i don't konw what is happend,  how can i get faster after doing int8 quantization in openvino ?

here is the download links of my onnx file:

链接: https://pan.baidu.com/s/1QUhs5wY1fsOVlzsCbsx7aw 提取码: tna9 复制这段内容后打开百度网盘手机App，操作更方便哦

链接: https://pan.baidu.com/s/1DHXTRxBGcPXpOAkPqZo0BQ 提取码: tc2j 复制这段内容后打开百度网盘手机App，操作更方便哦

thank you~

**Comment by ZhangZhiPku** [comment]
这是我的测试代码：

    # ---------------------------------------------------------------
    # 这个脚本向你展示了如何使用 openvino 对 PPQ 导出的模型进行推理
    # 你需要注意，openvino 也可以运行各种各样的量化方案，你甚至可以用 tensorRT 的 policy
    # 但总的来说，openvino 需要非对称量化的 activation 和对称量化的 weights
    # 现在的写法针对单输入网络哦，多输入的你得自己改改
    # ---------------------------------------------------------------
    
    # For this onnx inference test, all test data is randomly picked.
    # If you want to use real data, just rewrite the defination of SAMPLES
    import numpy as np
    import openvino
    import torch
    from tqdm import tqdm
    import time
    
    from ppq import *
    from ppq.api import *
    
    QUANT_PLATFROM    = TargetPlatform.PPL_CUDA_INT8
    BATCHSIZE         = 1
    DEVICE            = 'cuda'
    INPUTSHAPE        = [BATCHSIZE, 3, 640, 640]
    SAMPLES           = [torch.rand(size=INPUTSHAPE) for _ in range(256)]
    BENCHMARK_SAMPLES = 512
    MODEL_PATH        = 'modelzoo\yolo.onnx'
    VALIDATION        = False
    
    with ENABLE_CUDA_KERNEL():
        quantized = quantize_onnx_model(
            onnx_import_file=MODEL_PATH, calib_dataloader=SAMPLES, collate_fn=lambda x: x.to(DEVICE),
            calib_steps=32, input_shape=INPUTSHAPE,
            setting=QuantizationSettingFactory.default_setting(),
            platform=QUANT_PLATFROM)
    
        if VALIDATION:
            executor = TorchExecutor(graph=quantized)
            ref_results = []
            for sample in tqdm(SAMPLES, desc='PPQ GENERATEING REFERENCES', total=len(SAMPLES)):
                result = executor.forward(inputs=sample.to(DEVICE))[0]
                result = result.cpu().reshape([1, -1])
                ref_results.append(result)
    
        fp32_input_names  = [name for name, _ in quantized.inputs.items()]
        fp32_output_names = [name for name, _ in quantized.outputs.items()]
    
        graphwise_error_analyse(graph=quantized, running_device='cuda', 
                                dataloader=SAMPLES, collate_fn=lambda x: x.cuda(), steps=32)
    
        export_ppq_graph(
            graph=quantized, platform=TargetPlatform.OPENVINO_INT8,
            graph_save_to='model_int8.onnx')
    
    int8_input_names  = [name for name, _ in quantized.inputs.items()]
    int8_output_names = [name for name, _ in quantized.outputs.items()]
    
    # run with openvino.
    # do not use Tensorrt provider to run quantized model.
    # TensorRT provider needs another qdq format.
    if VALIDATION:
        import openvino.runtime
        openvino_executor = openvino.runtime.Core()
        model = openvino_executor.compile_model(
            model = openvino_executor.read_model(model="model_int8.onnx"), device_name="CPU")
        openvino_results = []
        for sample in tqdm(SAMPLES, desc='OPENVINO GENERATEING OUTPUTS', total=len(SAMPLES)):
            result = model([convert_any_to_numpy(sample)])
            for key, value in result.items():
                result = convert_any_to_torch_tensor(value).reshape([1, -1])
            openvino_results.append(result)
    
        # compute simulating error
        error = []
        for ref, real in zip(ref_results, openvino_results):
            error.append(torch_snr_error(ref, real))
        error = sum(error) / len(error) * 100
        print(f'PPQ INT8 Simulating Error: {error: .3f} %')
    
    # benchmark with openvino int8
    print(f'Start Benchmark with openvino (Batchsize = {BATCHSIZE})')
    benchmark_sample = np.zeros(shape=INPUTSHAPE, dtype=np.float32)
    benchmark_sample = convert_any_to_numpy(sample)
    
    model = openvino_executor.compile_model(
        model = openvino_executor.read_model(model="modelzoo\yolo.onnx"), device_name="CPU")
    tick = time.time()
    for iter in tqdm(range(BENCHMARK_SAMPLES), desc='FP32 benchmark...'):
        result = model([benchmark_sample])
    tok  = time.time()
    print(f'Time span (FP32 MODE): {tok - tick : .4f} sec')
    
    model = openvino_executor.compile_model(
        model = openvino_executor.read_model(model="model_int8.onnx"), device_name="CPU")
    tick = time.time()
    for iter in tqdm(range(BENCHMARK_SAMPLES), desc='INT8 benchmark...'):
        result = model([benchmark_sample])
    tok  = time.time()
    print(f'Time span (INT8 MODE): {tok - tick  : .4f} sec')

**Comment by ZhangZhiPku** [comment]
你可能需要 emm，买个新的cpu
我是12700k

**Comment by tuochi** [comment]
> 这是我的测试代码：
> 
> ```
> # ---------------------------------------------------------------
> # 这个脚本向你展示了如何使用 openvino 对 PPQ 导出的模型进行推理
> # 你需要注意，openvino 也可以运行各种各样的量化方案，你甚至可以用 tensorRT 的 policy
> # 但总的来说，openvino 需要非对称量化的 activation 和对称量化的 weights
> # 现在的写法针对单输入网络哦，多输入的你得自己改改
> # ---------------------------------------------------------------
> 
> # For this onnx inference test, all test data is randomly picked.
> # If you want to use real data, just rewrite the defination of SAMPLES
> import numpy as np
> import openvino
> import torch
> from tqdm import tqdm
> import time
> 
> from ppq import *
> from ppq.api import *
> 
> QUANT_PLATFROM    = TargetPlatform.PPL_CUDA_INT8
> BATCHSIZE         = 1
> DEVICE            = 'cuda'
> INPUTSHAPE        = [BATCHSIZE, 3, 640, 640]
> SAMPLES           = [torch.rand(size=INPUTSHAPE) for _ in range(256)]
> BENCHMARK_SAMPLES = 512
> MODEL_PATH        = 'modelzoo\yolo.onnx'
> VALIDATION        = False
> 
> with ENABLE_CUDA_KERNEL():
>     quantized = quantize_onnx_model(
>         onnx_import_file=MODEL_PATH, calib_dataloader=SAMPLES, collate_fn=lambda x: x.to(DEVICE),
>         calib_steps=32, input_shape=INPUTSHAPE,
>         setting=QuantizationSettingFactory.default_setting(),
>         platform=QUANT_PLATFROM)
> 
>     if VALIDATION:
>         executor = TorchExecutor(graph=quantized)
>         ref_results = []
>         for sample in tqdm(SAMPLES, desc='PPQ GENERATEING REFERENCES', total=len(SAMPLES)):
>             result = executor.forward(inputs=sample.to(DEVICE))[0]
>             result = result.cpu().reshape([1, -1])
>             ref_results.append(result)
> 
>     fp32_input_names  = [name for name, _ in quantized.inputs.items()]
>     fp32_output_names = [name for name, _ in quantized.outputs.items()]
> 
>     graphwise_error_analyse(graph=quantized, running_device='cuda', 
>                             dataloader=SAMPLES, collate_fn=lambda x: x.cuda(), steps=32)
> 
>     export_ppq_graph(
>         graph=quantized, platform=TargetPlatform.OPENVINO_INT8,
>         graph_save_to='model_int8.onnx')
> 
> int8_input_names  = [name for name, _ in quantized.inputs.items()]
> int8_output_names = [name for name, _ in quantized.outputs.items()]
> 
> # run with openvino.
> # do not use Tensorrt provider to run quantized model.
> # TensorRT provider needs another qdq format.
> if VALIDATION:
>     import openvino.runtime
>     openvino_executor = openvino.runtime.Core()
>     model = openvino_executor.compile_model(
>         model = openvino_executor.read_model(model="model_int8.onnx"), device_name="CPU")
>     openvino_results = []
>     for sample in tqdm(SAMPLES, desc='OPENVINO GENERATEING OUTPUTS', total=len(SAMPLES)):
>         result = model([convert_any_to_numpy(sample)])
>         for key, value in result.items():
>             result = convert_any_to_torch_tensor(value).reshape([1, -1])
>         openvino_results.append(result)
> 
>     # compute simulating error
>     error = []
>     for ref, real in zip(ref_results, openvino_results):
>         error.append(torch_snr_error(ref, real))
>     error = sum(error) / len(error) * 100
>     print(f'PPQ INT8 Simulating Error: {error: .3f} %')
> 
> # benchmark with openvino int8
> print(f'Start Benchmark with openvino (Batchsize = {BATCHSIZE})')
> benchmark_sample = np.zeros(shape=INPUTSHAPE, dtype=np.float32)
> benchmark_sample = convert_any_to_numpy(sample)
> 
> model = openvino_executor.compile_model(
>     model = openvino_executor.read_model(model="modelzoo\yolo.onnx"), device_name="CPU")
> tick = time.time()
> for iter in tqdm(range(BENCHMARK_SAMPLES), desc='FP32 benchmark...'):
>     result = model([benchmark_sample])
> tok  = time.time()
> print(f'Time span (FP32 MODE): {tok - tick : .4f} sec')
> 
> model = openvino_executor.compile_model(
>     model = openvino_executor.read_model(model="model_int8.onnx"), device_name="CPU")
> tick = time.time()
> for iter in tqdm(range(BENCHMARK_SAMPLES), desc='INT8 benchmark...'):
>     result = model([benchmark_sample])
> tok  = time.time()
> print(f'Time span (INT8 MODE): {tok - tick  : .4f} sec')
> ```

我看了这个脚本发现它是重新量化后导出model_int8.onnx再测试的，而且量化的平台和导出的平台不一样。我试着在TargetPlatform.PPL_CUDA_INT8 导出到openvino后速度稍微变快。想问一下你openvino运行时和开发是什么版本是呢？

不尽感谢~

**Comment by ZhangZhiPku** [comment]
我的环境是：
openvino                       2022.1.0
openvino-dev                2022.1.0
openvino-telemetry      2022.1.1

量化平台应该是我选错了，不过你发现了盲点，openvino这个玩意兼容性很强，它支持各种各样的量化方案。
量化平台确定了一种量化方案，它描述了以下内容：
1. 量化是否是对称的
2. 量化的粒度是 channelwise 还是 tensorwise
3. Round模式
4. 图融合策略与联合定点策略
5. 那些算子需要量化
6. 量化截断值是多少
7. 是否进行power-of-2的量化
8. 等等其他内容

openvino这个玩意同时支持对称、非对称量化；同时支持 per-channel 和 per-tensor 量化；只要你给了量化参数，它好像什么算子都可以量化。你的确可以修改它的量化策略来加速网络运行。
正常来说，速度最快的量化方式是对称 per-tensor 量化，它将比非对称 per-channel 快个30%左右。而显然你量化的算子越多，速度自然就会越快...但很遗憾，这些都是建立在openvino针对你的cpu写过高性能算子的基础上才会有加速效果，同时需要你的cpu支持向量化的指令集，比如sse2, avx512；我这cpu好像就没有avx512，在11700k上面的加速效果应该会更加明显。
