### ISSUE TITLE
ppq目前是否支持动态输入的onnx

### ISSUE THREAD

**Issue by pangr** [openppl-public/ppq#178]

**Comment by ZhangZhiPku** [comment]
支持的，你要往trt导出还是往哪导出？

**Comment by pangr** [comment]
> 
TensorRT，因为我使用动态输入的onnx进行量化后输出的是固定输入的int8的onnx

**Comment by pangr** [comment]
> batchsize还是写死吧，trt好像对dynamic batch的支持刚刚在8.4版本中更新，还不是很稳定。 如果你要动态输出的onnx，你可以参考下面的文件 https://github.com/openppl-public/ppq/blob/master/ppq/samples/dynamic_shape.py
> 
> 我们的infer_trt.py文件好像写的不能兼容动态batch，所以你可能需要自己写个推理的脚本

嗯嗯，好的，感谢回复
