### ISSUE TITLE
混合精度量化支持吗？会结合考虑实际板上推理速度吗？能否推荐一些确实work且好用的论文或方法~？

### ISSUE THREAD

**Issue by 666DZY666** [openppl-public/ppq#203]

**Comment by ZhangZhiPku** [comment]
你是说int 8/fp 16那种混合还是int 1/2/3/4/5/6/7/8那种混合？

**Comment by 666DZY666** [comment]
int 1/2/3/4/5/6/7/8

**Comment by 666DZY666** [comment]
谢谢回复~有没有比较好的4/8-bit混合精度搜索论文推荐？HAWQ？
之前ppq里的这部分为啥去掉了？想学习一下~

**Comment by ZhangZhiPku** [comment]
因为我们发现HAWQ算半天的效果还不如直接跑一下layerwise_analyse...

**Comment by 666DZY666** [comment]
okok~

**Comment by ZhangZhiPku** [comment]
容我晚些时候写一个例子给你，误差我会用snr，因为有数学依据啊...

**Comment by 666DZY666** [comment]
okok~

**Comment by 666DZY666** [comment]
关于误差，ppq里是看qt_output和fp_output的差距，
是否有实验过：1、qt_output和label的loss；2、qt_output和fp_output与label的loss的差距~?

**Comment by Jzz24** [comment]
> 关于误差，ppq里是看qt_output和fp_output的差距， 是否有实验过：1、qt_output和label的loss；2、qt_output和fp_output与label的loss的差距~?

不同网络loss计算方式不同，构建起来很“麻烦”，有时甚至不知道loss的设计，qat中需考虑任务loss，ptq的话直接衡量cos就行，常规模型cos(fp, int8)>0.99精度都满足，画质类要求更高一些

**Comment by 666DZY666** [comment]
okok~

**Comment by ZhangZhiPku** [comment]
@666DZY666 
你可以尝试下面这个文件中的内容，为了使得它能成功运行，你可能需要切换到我的开发分支上。

https://github.com/openppl-public/ppq/pull/207/files#diff-550e5d58f4eb3955decf84a9bdd7bdc7a7311843193260d12a240fd626390be7

**Comment by 666DZY666** [comment]
> 

okok，多谢~

**Comment by ZhangZhiPku** [comment]
@666DZY666 开发分支已经合并到主分支，现在你可以使用主分支上的内容完成测试了

**Comment by 666DZY666** [comment]
好的~

**Comment by 666DZY666** [comment]
demo中的bits是[4, 8]可选，若是[1, 4, 8, 16]呢？

**Comment by ZhangZhiPku** [comment]
那怕是你要自己写int1, int16平台quantizer对应的逻辑...
