### ISSUE TITLE
请问是否支持操作batch维度？

### ISSUE THREAD

**Issue by jzh1082** [openppl-public/ppq#214]
您好，我有一个输入为[15,3,512,512]的分割模型，在运行ProgramEntrance.py时提示“Error happens when dealing with operation Transpose_93(TargetPlatform.UNSPECIFIED) “，这个transpose是把第0个维度和第1个维度进行交换，请问是否支持这样的操作呢？

**Comment by ZhangZhiPku** [comment]
支持的，具体的错误在这个Error happens when dealing with operation Transpose_93(TargetPlatform.UNSPECIFIED)前面，你可以截一下前面的错误；Transpose 是支持的
