### ISSUE TITLE
squeeze 算子 axes参数为list时，forward存在问题。

### ISSUE THREAD

**Issue by wdian** [openppl-public/ppq#22]
![Dingtalk_20220304094349](https://user-images.githubusercontent.com/33274596/156683754-031d60fb-e018-4f5d-997b-3041bea1b536.jpg)

squeeze算子list时，ppq对 axes = axes[0]， 但output shape 会与实际onnx operator不一致，导致后续算子报错。同样问题可能也存在unsqueeze算子中。

我现在是通过for循环避免这个问题
![squeeze](https://user-images.githubusercontent.com/33274596/156683618-7c79128f-7e55-4c93-9710-aa315df00a69.jpg)

**Comment by Jzz24** [comment]
方便提供一下模型吗？修改后的onnxruntime和ppq fp32输出可以对齐吗？

**Comment by wdian** [comment]
> 方便提供一下模型吗？修改后的onnxruntime和ppq fp32输出可以对齐吗？

model: 
链接：https://pan.baidu.com/s/1w7vz2ZbeXmNROXAZtCQEcQ 
提取码：8888

**Comment by ZhangZhiPku** [comment]
这一问题已经在ppq 0.6.2中修复，Enjoy your day.
