### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ymzx** [openppl-public/ppq#221]
为什么在CPU本地跑ppq，会报CUDA相关编译错误？如何解决？
![image](https://user-images.githubusercontent.com/29808550/186842648-f8b60c34-ec7e-4959-b354-788eaaca21f1.png)

**Comment by ZhangZhiPku** [comment]
你的pytorch好像完全没装cuda，然后在lsq optimization方法里选了collecting device = cuda...请把它改成cpu

**Comment by ZhangZhiPku** [comment]
当然，我们更加建议你换个有gpu的电脑来跑量化：https://www.autodl.com/home

**Comment by ymzx** [comment]
> 

（1）已经指定了 executing_device = ‘cpu’，为什么后面程序还是出现cuda呢？
（2）修改 在lsq optimization方法collecting device = cuda. 的入口在哪里？

**Comment by ZhangZhiPku** [comment]
lsq那个collecting_device是独立的，默认是cuda
