### ISSUE TITLE
RuntimeError: Error happens when dealing with operation Conv_0

### ISSUE THREAD

**Issue by ymzx** [openppl-public/ppq#226]
RuntimeError: Error happens when dealing with operation Conv_0(TargetPlatform.NXP_INT8) - inputs:['input', '39', '40'], outputs:['38']

类似以上报错，可以从什么角度触发去debug？

**Comment by ZhangZhiPku** [comment]
这里是报告发生错误的算子，具体的错误在他前面，你可以截一下前面的错误内容
