### ISSUE TITLE
ppq对于国产gpu平台应该选择那个TargetPlatform

### ISSUE THREAD

**Issue by populustremble** [openppl-public/ppq#234]

**Comment by ZhangZhiPku** [comment]
啥gpu啊

**Comment by populustremble** [comment]
> 啥gpu啊

像寒武纪、华为的昇腾这些卡

**Comment by ZhangZhiPku** [comment]
如果你知道他们平台量化的具体规则，你可以使用这个脚本自己写一个Platform: https://github.com/openppl-public/ppq/blob/master/ppq/samples/Tutorial/targetPlatform.py
如果你不知道具体的量化规则，我们也可以帮你去问问...

**Comment by populustremble** [comment]
> 如果你知道他们平台量化的具体规则，你可以使用这个脚本自己写一个Platform: https://github.com/openppl-public/ppq/blob/master/ppq/samples/Tutorial/targetPlatform.py 如果你不知道具体的量化规则，我们也可以帮你去问问...

非常感谢，我去尝试一下写一个Platform

**Comment by ZhangZhiPku** [comment]
别忘了你可以抄我们现有的quantizer: https://github.com/openppl-public/ppq/blob/master/ppq/quantization/quantizer/TRTQuantizer.py

同时如果推理平台认onnx qdq的格式，你可以直接在导出的时候选择Targetplatform.ONNXRUNTIME
对应的导出逻辑会直接把你的量化方案以 onnx qdq格式导出

**Comment by YukSing12** [comment]
假如用了ppq里面的equalization，equalization后的权重还能保存回原始的pytorch模型里面吗？

**Comment by zhiqwang** [comment]
> 假如用了ppq里面的equalization，equalization后的权重还能保存回原始的pytorch模型里面吗？

这是要搞一个 ppq to pytorch 的功能嘛

**Comment by ZhangZhiPku** [comment]
@YukSing12 pytorch里面没有静态的模型，似乎没什么办法弄回去，equalization完了的权重可以存到onnx里面倒是真的

**Comment by zhiqwang** [comment]
> pytorch里面没有静态的模型，似乎没什么办法弄回去，equalization完了的权重可以存到onnx里面倒是真的

@ZhangZhiPku fx is all you need, https://github.com/ENOT-AutoDL/onnx2torch 这里采取的技术路线就是 torch.fx

**Comment by YukSing12** [comment]
> @YukSing12 pytorch里面没有静态的模型，似乎没什么办法弄回去，equalization完了的权重可以存到onnx里面倒是真的

那请问现在有没有什么方法可以获取equalization完了的权重呢？
