### ISSUE TITLE
how to load onnx/json into executor??

### ISSUE THREAD

**Issue by xingmimfl** [openppl-public/ppq#250]
how to load quantized onnx and json into TorchExecutor?

**Comment by xingmimfl** [comment]
> You can not load a quantized onnx into ppq. Not for now. 你不能加载一个已经量化过的模型进入ppq，至少现在不行。 如果你得模型是由ppq完成量化的，你可以选择导出平台为TargetPlatfrom.Native，这样你就会得到一个二进制的量化存档文件，这个文件可以被ppq所读取（包含了所有量化信息）。

另外一个问题。quantized = quantize_torch_model()，我后面接一个torch.save(quantized, 'model_ppq_quantized.pt')， 但是奇怪的是当torch.load('model_ppq_quantized.pt')的时候出现问题

**Comment by ZhangZhiPku** [comment]
你需要使用 export_ppq_graph(quantized, TargetPlatform.Native) 导出二进制的 ppq 量化存档文件，直接pickle.dump()或者torch.save并不可以。
同时你需要使用load_native_graph导入存档文件。
