### ISSUE TITLE
Targetplatform enum  值有什么特定的含义么？

### ISSUE THREAD

**Issue by huoshuai-dot** [openppl-public/ppq#252]
比如https://github.com/openppl-public/ppq/blob/d7097a7fc22e0ed83b688d1b1c15c0ba284d9ecd/ppq/core/quant.py#L99
这个里面的10081 ，如果新增platform时这个值是否可以随意取一个之前没配置过的值？

**Comment by ZhangZhiPku** [comment]
是的，你可以随便弄个新的，没什么特别的意思，别重复就行
