### ISSUE TITLE
conv 量化误差过大？

### ISSUE THREAD

**Issue by hufangjian** [openppl-public/ppq#258]
请问一下我这边有个模型，量化分析的时候误差比较大，这个怎么优化处理？选的TargetPlatform.PPL_CUDA_INT8  默认设置。
![image](https://user-images.githubusercontent.com/30458099/193197735-54f4a20a-b77c-4180-8212-fbc0e2343490.png)

**Comment by ZhangZhiPku** [comment]
请把conv38, conv37送回到fp32

**Comment by Lenan22** [comment]
> 请问一下我这边有个模型，量化分析的时候误差比较大，这个怎么优化处理？选的TargetPlatform.PPL_CUDA_INT8 默认设置。 ![image](https://user-images.githubusercontent.com/30458099/193197735-54f4a20a-b77c-4180-8212-fbc0e2343490.png)

如果使用了优化算法，网络的中间某一层出现的误差较大，是正常的情况(无标签训练有时会出现这种情况)，具体要看最后一层的模拟误差以及在硬件上跑的效果
