### ISSUE TITLE
强制联合定点的一些疑惑

### ISSUE THREAD

**Issue by huoshuai-dot** [openppl-public/ppq#259]
1、https://github.com/openppl-public/ppq/blob/4367e26d976dc3d7485d591b647d6af74c5eb597/ppq/quantization/optim/refine.py#L650
这段代码里面取出了method的值但是 有没有使用 是不是实现的问题，以及下一句 Align to Large 重复了两次 应该是写错了吧
2、这段的强制联合定点手动覆盖 该怎么理解呢？

**Comment by ZhangZhiPku** [comment]
啊是的，这里有个bug，我会尽快修复。

在算子上有一个属性字段叫operation.extension_attrib，这里面是个字典。这是为了扩充一些不那么必要的属性而设计的，用户也可以往里面放一些自己所需要的东西，从而通过operation进行传递。

你可以使用这个属性手动覆盖observer, 联合定点，还有一些其他别的什么设置，我们也会不断的往其中添加新的内容。
你可以在ppq.core.common里面看到有哪些属性是正在被ppq所使用的。
