### ISSUE TITLE
如何设置engine max batch size？

### ISSUE THREAD

**Issue by 18242360613** [openppl-public/ppq#260]
你好，我在跑yolo样例代码时，利用02_Quantization.py代码生成了batchsize 为32的int8量化的tensorrt的engine（基于yolov6s模型），利用04_Benchmark.py进行评估时，报一下错误。
[executionContext.cpp::enqueue::282] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueue::282, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 32, but engine max batch size was: 1

已经检查过对应生产的onnx模型，输入输出确实是以32为batch_size的。

求大佬指教一下。

**Comment by ZhangZhiPku** [comment]
你可以看到ppq.parser.tensorRT.py 196行处有一段相关的代码，并直接给他写个32上去

**Comment by 18242360613** [comment]
我检查了ppq.parser.tensorRT.py 196行处的代码input_shapes已经被设置为[32,3,640,640],并且在247行for循环后添加了下面的代码，设置了proile，min.opt，max的尺寸都是[32,3,640,640]。
            min, opt, max = input_shapes[inp.name]
            profile.set_shape_input(inp.name, min, opt, max)
            
            config.add_optimization_profile(profile)
            trt_engine = builder.build_engine(network, config)
但是还是会出现上面这个问题。

后来我修改了04_Benchmark.py中的代码，将batch_size设置成了1,将inputshape设置成了[32,3,640,640],代码也可以运行，相对于fp32的也实现了快10倍的加速（基于3090显卡）。

ENGINE_PATH = '/home/cp/git/ppq/model/yolov6s_ppq_int8_b32.engine'
BATCH_SIZE  = 1
INPUT_SHAPE = [32, 3, 640, 640]
BENCHMARK_SAMPLES = 51200

print(f'Benchmark with {ENGINE_PATH}')
logger = trt.Logger(trt.Logger.ERROR)
with open(ENGINE_PATH, 'rb') as f, trt.Runtime(logger) as runtime:
    engine = runtime.deserialize_cuda_engine(f.read())

with engine.create_execution_context() as context:
    inputs, outputs, bindings, stream = trt_infer.allocate_buffers(context.engine)
    inputs[0].host = np.zeros(shape=INPUT_SHAPE, dtype=np.float32)

    for _ in tqdm(range(BENCHMARK_SAMPLES), desc=f'Benchmark ...'):
        output = trt_infer.do_inference(
            context, bindings=bindings, inputs=inputs, 
            outputs=outputs, stream=stream, batch_size=BATCH_SIZE)
      
但是原来的代码上面batchsize和inputshape都是基于32，如果我将batchsize和inputshape都设置成32。代码就会报错，和上面的错误一样。这里面还有什么地方有问题吗？

**Comment by 18242360613** [comment]
我检查了ppq.parser.tensorRT.py 196行处的代码input_shapes已经被设置为[32,3,640,640],并且在247行for循环后添加了下面的代码，设置了proile，min.opt，max的尺寸都是[32,3,640,640]。
            min, opt, max = input_shapes[inp.name]
            profile.set_shape_input(inp.name, min, opt, max)
            
            config.add_optimization_profile(profile)
            trt_engine = builder.build_engine(network, config)
但是还是会出现上面这个问题。

后来我修改了04_Benchmark.py中的代码，将batch_size设置成了1,将inputshape设置成了[32,3,640,640],代码也可以运行，相对于fp32的也实现了快10倍的加速（基于3090显卡）。

ENGINE_PATH = '/home/cp/git/ppq/model/yolov6s_ppq_int8_b32.engine'
BATCH_SIZE  = 1
INPUT_SHAPE = [32, 3, 640, 640]
BENCHMARK_SAMPLES = 51200

print(f'Benchmark with {ENGINE_PATH}')
logger = trt.Logger(trt.Logger.ERROR)
with open(ENGINE_PATH, 'rb') as f, trt.Runtime(logger) as runtime:
    engine = runtime.deserialize_cuda_engine(f.read())

with engine.create_execution_context() as context:
    inputs, outputs, bindings, stream = trt_infer.allocate_buffers(context.engine)
    inputs[0].host = np.zeros(shape=INPUT_SHAPE, dtype=np.float32)

    for _ in tqdm(range(BENCHMARK_SAMPLES), desc=f'Benchmark ...'):
        output = trt_infer.do_inference(
            context, bindings=bindings, inputs=inputs, 
            outputs=outputs, stream=stream, batch_size=BATCH_SIZE)
      
但是原来的代码上面batchsize和inputshape都是基于32，如果我将batchsize和inputshape都设置成32。代码就会报错，和上面的错误一样。这里面还有什么地方有问题吗？

**Comment by ZhangZhiPku** [comment]
这...可就不知道咋回事了
