### ISSUE TITLE
TypeError: quantize_onnx_model() missing 1 required positional argument: 'platform'

### ISSUE THREAD

**Issue by Jianchun-Huo** [openppl-public/ppq#275]
你好，当我尝试使用quantize_onnx_model时，出现了以下错误TypeError: quantize_onnx_model() missing 1 required positional argument: 'platform'

代码：
```python
sample_input = [torch.rand(1,3,640,640) for i in range(32)]
ir = quantize_onnx_model(
    onnx_import_file='./working/best.onnx',
    calib_dataloader=sample_input,
    calib_steps=16,
    do_quantize=False,
    input_shape=None,
    collate_fn=lambda x:x.to('cuda'),
    inputs=torch.rand(1,3,640,640).to('cuda')
)
executor = TorchExecutor(ir)
```

请问这里的platform该设置什么值呢？

**Comment by Lenan22** [comment]
> 你好，当我尝试使用quantize_onnx_model时，出现了以下错误TypeError: quantize_onnx_model() missing 1 required positional argument: 'platform'
> 
> 代码：
> 
> ```python
> sample_input = [torch.rand(1,3,640,640) for i in range(32)]
> ir = quantize_onnx_model(
>     onnx_import_file='./working/best.onnx',
>     calib_dataloader=sample_input,
>     calib_steps=16,
>     do_quantize=False,
>     input_shape=None,
>     collate_fn=lambda x:x.to('cuda'),
>     inputs=torch.rand(1,3,640,640).to('cuda')
> )
> executor = TorchExecutor(ir)
> ```
> 
> 请问这里的platform该设置什么值呢？
请问你的模型要部署到哪个推理库呢？

**Comment by Jianchun-Huo** [comment]
我想使用的是pytorch cuda进行推理，然后使用Profiler来进行网络性能分析，参照[教程视频链接](https://www.bilibili.com/video/BV1oT4y1h73e/)

**Comment by ZhangZhiPku** [comment]
你可以在quantize_onnx_model调用中追加一个参数 platform = TargetPlatform.TRT_INT8

**Comment by Jianchun-Huo** [comment]
问题已解决，谢谢~

**Comment by LameloChen** [comment]
怎么解决的呢，我也遇到这个问题

**Comment by LameloChen** [comment]
也是学习的这个视频
