### ISSUE TITLE
darknet 模型如何量化

### ISSUE THREAD

**Issue by charles-str** [openppl-public/ppq#276]
现在模型是yolov4 的darknet模型 ，请问如何量化呢？

**Comment by Lenan22** [comment]
> 现在模型是yolov4 的darknet模型 ，请问如何量化呢？

理论上可以把darknet转换为onnx or caffe，然后再用ppq量化部署，模型可以发来我，我看下?   cugb_wulenan@163.com

**Comment by charles-str** [comment]
tx2 ,tensorrt 5.0

**Comment by Lenan22** [comment]
> tx2 ,tensorrt 5.0

tx2不支持int8，后续我们会出一个darknet模型的量化部署的文档分享给你

**Comment by Lenan22** [comment]
> tx2 ,tensorrt 5.0

https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md      参考这个文档即可用tensorrt自带的api量化部署，python和c++都写了demo

**Comment by charles-str** [comment]
好的，谢谢，有有问题再请假



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月28日(周五) 上午8:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [openppl-public/ppq] darknet 模型如何量化 (Issue #276)




  
tx2 ,tensorrt 5.0
  
https://github.com/openppl-public/ppq/blob/master/md_doc/deploy_trt_by_api.md      参考这个文档即可用tensorrt自带的api量化部署，python和c++都写了demo
