### ISSUE TITLE
反卷中似乎存在bug

### ISSUE THREAD

**Issue by Sherrywangyuan** [openppl-public/ppq#282]
我不确定这里是否存在bug，我认为在operation.type == 'ConvTranspose'时，channel_axis应该为1，否则后续量化时维度对不上。
https://github.com/openppl-public/ppq/blob/6e2826c2f529ebbe351ba4271f112fd8265611f4/ppq/quantization/quantizer/TRTQuantizer.py#L49

不过一直没人报告过这个问题，我不知道我的判断是否正确。

**Comment by ZhangZhiPku** [comment]
是的，在0.6.6中我已经改过来了

**Comment by Sherrywangyuan** [comment]
好的，谢谢。
