### ISSUE TITLE
3d detection

### ISSUE THREAD

**Issue by shuyuan-wang** [openppl-public/ppq#289]
Have you guyes tried int8 quantization on 3d detection network, like Centerpoint? How's the performance?

**Comment by ZhangZhiPku** [comment]
我们好像还没有业务做3d检测网络，但是ppq的量化策略以及算法部分的确支持3d卷积。

精度方面与2d 3d卷积没啥直接关系，不同的网络就会有不一样的表现。
性能方面则需要看你部署在什么框架上。以TensorRT为例，完成量化后你需要使用 nsight profiler 或者 https://github.com/NVIDIA/TensorRT/tree/main/tools/experimental/trt-engine-explorer 执行性能分析。
