### ISSUE TITLE
ppq目前是不支持GatherTopk op吗？

### ISSUE THREAD

**Issue by shhn1** [openppl-public/ppq#302]
我用onnx模型转TRT_INT8时，出现了下面这个报错：
<img width="941" alt="截屏2022-11-17 21 02 34" src="https://user-images.githubusercontent.com/55838930/202454544-890f4681-70e9-4756-87eb-d182c1ba4e2d.png">

**Comment by Lenan22** [comment]
对了，还需要卸载ppq-0.6.6-*

**Comment by ZhangZhiPku** [comment]
Topk下面的就是GatherTopk，我们好像确实没写这玩意的执行函数，让我来补一个

**Comment by shhn1** [comment]
好嘞，感谢！

**Comment by shhn1** [comment]
> 在你网络中Topk下面的就是GatherTopk，我们好像确实没写这玩意的执行函数。
> 
> 我没有在 onnx 的定义中找到这个算子：https://github.com/onnx/onnx/blob/main/docs/Operators.md
> 
> 这是你自己定义的算子吗？

这不是我自定义的算子呀

**Comment by ZhangZhiPku** [comment]
onnx 没有这个算子的定义，是不是你使用的算法库自己定义的？

你最好不要导出这个算子，即使你为 ppq 完成了算子的注册，推理库也不知道如何处理这个算子，以 TensorRT 为例，你需要使用 cuda 自己手写一个这个算子的实现注册。我建议你把他换成别的算子

**Comment by shhn1** [comment]
好的，我试试把这个模型分成两部分，只对backbone中的swin-transformer进行量化。我看swin transformer中的op主要是Reshape，Transpose，MatMul，add，Mul这些，ppq会对这些进行量化吗？量化之后导出的这种transformer- based network TRT_INT8，是可以在TensorRT的平台上推理嘛？

**Comment by ZhangZhiPku** [comment]
好家伙你也是transformer是吧，你可以偷偷加我的qq:281077761，我想个办法让你放弃幻想

**Comment by shhn1** [comment]
好的，感谢大佬！

**Comment by lyyiangang** [comment]
> 

说出来听听啊，我也在看trasformer，也需要摈弃幻想

**Comment by aksenventwo** [comment]
说出来听听啊，我也在看trasformer，也需要摈弃幻想

**Comment by ZhangZhiPku** [comment]
> 说出来听听啊，我也在看trasformer，也需要摈弃幻想

你可以偷偷加我的qq...
