### ISSUE TITLE
导出器的 ONNX 默认 domain 应该留空而不是写 "ai.onnx"

### ISSUE THREAD

**Issue by Goose-Bomb** [openppl-public/ppq#307]
https://github.com/openppl-public/ppq/blob/defeeaf1a8ae8883167387dd222581721984d08b/ppq/parser/onnxruntime_exporter.py#L358

应该改成

```python3
extra_domain_versions = [('', 13)]
```

这样下面的 ONNX Checker 就能检查通过了
```python3
onnx.checker.check_model(onnx_model)
```

**Comment by ZhangZhiPku** [comment]
我会遵循你的写法把它改一下。

这个onnx checker检查的很严格，不是运行的必要条件，你可以不管他直接导出。
如果checker报错你也可以直接给他注释掉，onnxruntime也能正常的去执行。
