### ISSUE TITLE
RKNN平台量化使用怎么样选择量化配置？

### ISSUE THREAD

**Issue by masommao** [openppl-public/ppq#316]
您好，我现在想用ppq量化我的离线pytorch模型，部署硬件平台是rk的板端，TargetPlatform.RKNN_INT8，怎么选配置？是QuantizationSettingFactory.trt_setting()吗？量化出来生成二个文件，一个是onnx的模型，还有一个是json文件，我只要用onnx模型转rknn模型就可以还是我要使用onnx和json一起使用转rknn模型？rknn模型是最终部署到板端的模型。注：转rknn是在带1080GPU电脑上完成。

**Comment by ZhangZhiPku** [comment]
请参考下面的例子完成量化 

    # For this onnx inference test, all test data is randomly picked.
    # If you want to use real data, just rewrite the defination of SAMPLES
    
    import torch
    from ppq import *
    from ppq.api import *
    from tqdm import tqdm
    
    QUANT_PLATFROM = TargetPlatform.RKNN_INT8
    MODEL          = 'models\\resnet18.onnx'
    INPUT_SHAPE    = [1, 3, 224, 224]
    SAMPLES        = [torch.rand(size=INPUT_SHAPE) for _ in range(256)] # rewirte this to use real data.
    DEVICE         = 'cuda'
    FINETUNE       = False
    QS             = QuantizationSettingFactory.default_setting()
    EXECUTING_DEVICE = 'cuda'
    REQUIRE_ANALYSE  = True
    
    # -------------------------------------------------------------------
    # 下面向你展示了常用参数调节选项：
    # -------------------------------------------------------------------
    QS.lsq_optimization = FINETUNE                                  # 启动网络再训练过程，降低量化误差
    QS.lsq_optimization_setting.steps = 500                         # 再训练步数，影响训练时间，500 步大概几分钟
    QS.lsq_optimization_setting.collecting_device = 'cuda'          # 缓存数据放在那，cuda 就是放在 gpu，如果显存超了你就换成 'cpu'
    
    # 把量化的不太好的算子送回 FP32
    QS.dispatching_table.append(operation='OP NAME', platform=TargetPlatform.FP32)
    
    print('正准备量化你的网络，检查下列设置:')
    print(f'TARGET PLATFORM      : {QUANT_PLATFROM.name}')
    print(f'NETWORK INPUTSHAPE   : {INPUT_SHAPE}')
    
    # ENABLE CUDA KERNEL 会加速量化效率 3x ~ 10x，但是你如果没有装相应编译环境的话是编译不了的
    # 你可以尝试安装编译环境，或者在不启动 CUDA KERNEL 的情况下完成量化：移除 with ENABLE_CUDA_KERNEL(): 即可
    with ENABLE_CUDA_KERNEL():
        qir = quantize_onnx_model(
            onnx_import_file=MODEL, calib_dataloader=SAMPLES, calib_steps=128, setting=QS,
            input_shape=INPUT_SHAPE, collate_fn=lambda x: x.to(EXECUTING_DEVICE), 
            platform=QUANT_PLATFROM, do_quantize=True)
    
        # -------------------------------------------------------------------
        # PPQ 计算量化误差时，使用信噪比的倒数作为指标，即噪声能量 / 信号能量
        # 量化误差 0.1 表示在整体信号中，量化噪声的能量约为 10%
        # 你应当注意，在 graphwise_error_analyse 分析中，我们衡量的是累计误差
        # 网络的最后一层往往都具有较大的累计误差，这些误差是其前面的所有层所共同造成的
        # 你需要使用 layerwise_error_analyse 逐层分析误差的来源
        # -------------------------------------------------------------------
        print('正计算网络量化误差(SNR)，最后一层的误差应小于 0.1 以保证量化精度:')
        reports = graphwise_error_analyse(
            graph=qir, running_device=EXECUTING_DEVICE, steps=32,
            dataloader=SAMPLES, collate_fn=lambda x: x.to(EXECUTING_DEVICE))
        for op, snr in reports.items():
            if snr > 0.1: ppq_warning(f'层 {op} 的累计量化误差显著，请考虑进行优化')
    
        if REQUIRE_ANALYSE:
            print('正计算逐层量化误差(SNR)，每一层的独立量化误差应小于 0.1 以保证量化精度:')
            layerwise_error_analyse(graph=qir, running_device=EXECUTING_DEVICE,
                                    interested_outputs=None,
                                    dataloader=SAMPLES, collate_fn=lambda x: x.to(EXECUTING_DEVICE))
    
        print('网络量化结束，正在生成目标文件:')
        export_ppq_graph(
            graph=qir, platform=TargetPlatform.ONNXRUNTIME,
            graph_save_to = 'model_int8.onnx')

**Comment by ZhangZhiPku** [comment]
上述文件会生成一个带有 qdq 节点的 onnx 文件，你可以使用 rknn_toolchain 2.0 完成部署，期间遇到问题可以随时与我们联系

**Comment by zhaoxin111** [comment]
> 上述文件会生成一个带有 qdq 节点的 onnx 文件，你可以使用 rknn_toolchain 2.0 完成部署，期间遇到问题可以随时与我们联系

大佬，我想通过ppq转onnx到rknn。我通过最新版(0.6.6)转出qdq节点的onnx了，但使用[rknn_toolkit2.0](https://github.com/rockchip-linux/rknn-toolkit2)转换时候遇到rknn无法识别ppq名字的量化节点
![image](https://github.com/openppl-public/ppq/assets/9295202/77137d22-c4de-43ac-8291-613be1c957d4)
请问这是什么问题呀？
