### ISSUE TITLE
tf graph支持

### ISSUE THREAD

**Issue by mrj-taffy** [openppl-public/ppq#32]
你好，请教下，ppq目前主要是针对torch及相应的onnx支持，针对tensorflow model的量化（pb），需要转onnx，或者有什么使用建议吗？

**Comment by ZhangZhiPku** [comment]
对于tensorflow而言，其转出来的onnx可能跟torch的不太一样，但只要模型符合onnx的定义，ppq是有能力完成量化任务的。我们害怕的是对于计算类型的算子，比如Gemm或者Conv，tensorflow导出onnx时是否会把这些算子拆分成更细粒度的算子，例如Matmul+Add, Pad+Conv的形式，一旦发生此类情况，则我们的量化无法很好的适配这样的模型。为此我们势必需要对类似的情况进行算子规范化，而PPQ已经写了不少类似的代码。
由于我们从未尝试过量化来自tensorflow的模型文件，当你在此过程中遇到任何无法解决的问题时，欢迎及时与我们取得联系，这是tensorflow量化道路上的重要一步。（你需要注意我们目前只支持op set 11哦）

**Comment by mrj-taffy** [comment]
@ZhangZhiPku 情况基本了解，谢谢！

**Comment by ZhangZhiPku** [comment]
我们最近转换了一些tensorflow的模型，总体没有遇到太多障碍，最多的障碍就是tensorflow的模型转出来很多不是opset11的，你可以使用onnx的官方工具将它们转换到opset11，之后就没啥大问题了。

https://github.com/onnx/onnx/blob/main/docs/VersionConverter.md
