### ISSUE TITLE
怎么看模型适不适合量化，能不能从量化中获益？

### ISSUE THREAD

**Issue by zuowanbushiwo** [openppl-public/ppq#322]
你好 
      从B站视频了解这个项目的，B站的视频讲得很清楚，已经一键三连。视频中提到有些网络从量化中并不能获益，可能还有负反馈，但是没提到怎么详细的判断，就怕一顿操作猛如虎，一看结果二百五。
    这个和平台，推理框架有关吗？比如考虑android，arm64, ncnn 这个方向有什么好的判断准则吗？
谢谢！

**Comment by zuowanbushiwo** [comment]
@ZhangZhiPku 
带lstm的crnn模型 目前可以 ncnn int8量化吗？像下面这样的网络
![image](https://user-images.githubusercontent.com/3354428/206606947-6ece42bb-49ff-4af3-b0b4-0e45100b729f.png)

**Comment by ZhangZhiPku** [comment]
@zuowanbushiwo 
我们很高兴视频中的内容能够帮助到你，视频中的内容从逻辑层面解释了量化是如何加速你的神经网络的。

从物理层面，或者说实现层面，应当注意到不同的推理库、不同的硬件之间存在较大的差异性，因此你需要使用 ncnn 自带的性能分析工具来辅助判断：https://github.com/Tencent/ncnn/tree/master/benchmark

#### 我们将以一个例子告诉你性能分析工具是如何帮助我们设计量化策略的
我们假设你的网络结构形如: Conv1-Conv2-Conv3-Lstm1-Conv4-Conv5-Conv6，性能分析工具会报告每一层的执行所需时间，你将看到类似下面的结果：

    Conv1: 7ms
    Conv2: 6ms
    Conv3: 7ms
    Lstm1: 9ms
    ...

你可以尝试量化其中的个别层，假设我们单独量化 Conv1。而后以量化后的模型重新运行性能测试，你将看到类似这样的结果：

    Float2Int: 3ms
    Conv1: 3ms
    Int2Float: 2ms
    Conv2: 6ms
    Conv3: 7ms
    Lstm1: 9ms
    ...

Float2Int, Int2Float 是由于 Conv1 被量化，辅助数据完成类型转换的算子。不同的推理框架对这类算子叫法不同，但作用类似。
此时为了完成数据转换，我们额外耗费了5ms时间，此时量化的性能收益为 7 - (3+3+2) = -2ms。

 为此我们可以尝试将 Conv1, Conv2, Conv3 全部量化，从而平摊数据类型转换的开销：

    Float2Int: 3ms
    Conv1: 3ms
    Conv2: 3ms
    Conv3: 3ms
    Int2Float: 2ms
    Lstm1: 9ms
    ...

于是我们此时的量化收益来到了 6ms，这相当于将原有网络提速了 20%。

#### 请注意，量化后的卷积是否能够加速运行，要依赖于推理框架的实现和硬件的支持

你可能会遇到这样的情况，一些算子量化之后比浮点还要更慢，这样的情况是完全可以发生的，大部分情况下是由于推理框架没有针对int8展开优化，或者硬件没有提供Int8的指令支持。在性能分析工具中你同样可以清楚地发现这类问题，这种情况下你无需考虑量化作为网络加速的手段。

**Comment by zuowanbushiwo** [comment]
好的，谢谢志佬。
这种让某些层量化，某些层不量化 PPQ 有参考例子吗？
