### ISSUE TITLE
请教一下导出到onnx的问题

### ISSUE THREAD

**Issue by Pzzzzz5142** [openppl-public/ppq#329]
在使用 `ONNXRUNTIME` 平台导出时，我有如下几个问题：
1. 问题 1：
    以一个 conv 为例：
    <img width="210" alt="image" src="https://user-images.githubusercontent.com/31173671/207376895-fcbf1b96-fc9b-4116-8a41-e81b18f2c078.png">

    这里 ppq 量化出来的结果是这样的：
    <img width="335" alt="image" src="https://user-images.githubusercontent.com/31173671/207377045-604a4aa4-f2bd-4673-9226-c4ab44994ef1.png">

    令我感到疑惑的点在于为何是先 quant 再 dequant？这样不就是依然在用 fp32 计算 conv 了吗？
2. 问题 2:
    在指定 shape 之后，似乎在 quant 和 dequant 算子中并没有关于 shape 的额外描述。而只在其他地方有关于 shape 的描述，请问一下这是正常的吗？因为我在后续开发中没有这个信息可能还得额外处理一下。
    <img width="384" alt="image" src="https://user-images.githubusercontent.com/31173671/207378300-8914efa6-f866-4f12-a7c4-5e853a23f85b.png">
3. 问题 3：
    同样是那个 demo 代码，似乎是新版本的 `export_ppq_graph` 函数新增了一个 `config_save_to` 参数。这个参数看起来是用来描述每一个 tensor 的量化策略的。请问一下如果我拿到了完整的 onnx model，是不是这些 policy 就已经存放在 onnx 里了，从而不需要管这个 config 文件呢？（同时那个 policy 里面的 LINEAR 是什么意思不太明白，但看起来好像所有 LINEAR 属性的值都是 true，是不是不用管（（）

烦请赐教！

**Comment by Pzzzzz5142** [comment]
感谢回复！

**Comment by Pzzzzz5142** [comment]
另，目前ppq在int8上表现不好的原因有可能就是因为导出格式的问题所导致的。因为相比未量化的模型，ppq导出的模型不仅额外引入了量化与反量化的操作，还使用了fp32进行计算。这里onnx官方的int8模型并不是这样导出的，而是使用了 `QLinearConv` 等量化数据专用算子进行运算。如图所示：
<img width="412" alt="image" src="https://user-images.githubusercontent.com/31173671/207586742-f7f83b38-04e0-4758-a7b4-bd697f8c3532.png">
同时 onnx 官方给的 int8 模型也考虑到了图优化，并没有频繁的插入反量化算子，供参考。

**Comment by vacing** [comment]
> 

模型只是一种表示，实际推理ort 还会对图做一次优化，最终也是走的linearconv 和linearadd
