### ISSUE TITLE
maxpool 输出没有量化参数

### ISSUE THREAD

**Issue by hufangjian** [openppl-public/ppq#336]
![image](https://user-images.githubusercontent.com/30458099/209539909-b71cf229-6fe2-4bb3-8d55-74dc2c321463.png)
使用
TargetPlatform.PPL_CUDA_INT8

**Comment by ZhangZhiPku** [comment]
在 PPQ 中， maxpooling 是一个被动量化的算子，这意味着maxpooling的输入和输出量化将被屏蔽
如果要显示maxpooling算子的量化信息，可以在 ppq\quantization\quantizer\PPLQuantizer.py 文件中进行修改

在  init_quantize_config 函数中添加对于 maxpool 的额外处理：
    
    from ppq.core import QuantizationVisibility
    if operation.type == 'MaxPool':
        for cfg in base_quant_config.output_quantization_config:
            cfg.visibility = QuantizationVisibility.FORCE_EXPORT

**Comment by hufangjian** [comment]
已解决，多谢。
