### ISSUE TITLE
模型量化算子改变

### ISSUE THREAD

**Issue by hufangjian** [openppl-public/ppq#337]
原先的算子是batchmorm量化后输出的onnx的算子变成卷积

![image](https://user-images.githubusercontent.com/30458099/209600896-768305d0-f2f1-4fd4-9972-e6d72dd7f7d7.png)

**Comment by ZhangZhiPku** [comment]
很多推理框架不允许你的网络中出现单独的batchnorm，它们无法实现推理，ppq也不会去量化单独的batchnorm。为此ppq会在读取onnx文件时识别这些单独的batchnorm并将他们替换成卷积。

如果你想关闭该行为，则在ppq\api\interface.py文件中修改format_graph.py函数，并移除 FORMAT_SNG_BN 指令即可

**Comment by hufangjian** [comment]
我这边对比了原始的模型，和bn转成group conv的模型，相同的输入，用onnxruntime比较，结果对不上。

**Comment by ZhangZhiPku** [comment]
你的模型似乎除了batchnorm这里还存在另外的问题，convtranpose后面的add似乎是一个bias add，但它并没有完成合并，而当bias add与convtranspose完成合并之后，后面的bn将可以直接合并到convtranspose当中

**Comment by hufangjian** [comment]
是的，用的onnxsim合并的。但是onnxsim 没有将convtranpose+bias+batchnorm合并。
convtranpose 自己手动可以按照这种方式合并吗？
https://blog.csdn.net/zym19941119/article/details/84635371
