### ISSUE TITLE
convTranpose perchannel量化权重scale维度不正确，

### ISSUE THREAD

**Issue by hufangjian** [openppl-public/ppq#339]
使用TargetPlatform.PPL_CUDA_INT8
正常卷积量化 x_scale 的维度和下面的相同。
![image](https://user-images.githubusercontent.com/30458099/209742459-62220478-5b9f-4a2b-9c9c-8504f0c4a295.png)

convTranpose量化
x_scale的维度是1，不是64
![image](https://user-images.githubusercontent.com/30458099/209742612-3476adb6-76bd-4460-9fe7-5322f305ae38.png)

**Comment by Jzz24** [comment]
convtranspose和conv的weight纬度不一样的，前者在onnx中的定义：

**Comment by ZhangZhiPku** [comment]
在 PPLQuantizer 中你可以发现这样的语句

conv_weight_config.channel_axis = (1 if operation.type == 'ConvTranspose' else 0)

对于 ConvTranspose 而言，它的参数量化通常沿着第二个轴进行，而非第一个。我们不清楚你最后打算使用怎样的框架完成推理，或许这些推理框架的确是使用第一个轴量化的 ConvTranspose。
但如果使用第一个轴进行量化，将导致bn无法合并等问题。

你可以手动修改 Quantizer 中的代码来指定一个新的量化轴。

**Comment by hufangjian** [comment]
感谢，convtranspose的perchannel量化应该是第二个轴的，convtranspose filter（0，1轴）和常规conv的（0，1轴）相反的。
常规conv 0轴是对应的输出channel，1轴对应的上输入channel。convtranspose 0轴对应的输入channel，1轴对应的输出channel。perchannel量化的对应的是每个输出channel一个量化scale，所以是1轴量化。
