### ISSUE TITLE
ppq量化后带有量化信息的onnx如何导出？

### ISSUE THREAD

**Issue by shuyuan-wang** [openppl-public/ppq#345]
是否有办法到处带有量化信息的onnx？比如带quantizeLinear在onnx里面

**Comment by ZhangZhiPku** [comment]
import ppq.api as API
    from ppq import TargetPlatform
    graph = API.load_onnx_graph('123.onnx')
    
    quantized = API.quantize_onnx_model(
        onnx_import_file=graph, 
        calib_dataloader=..., 
        calib_steps=8, 
        input_shape=..., 
        platform=TargetPlatform.ONNXRUNTIME)
    
    from ppq.parser import OnnxExporter, ONNXRUNTIMExporter
    
    # 这个没有 QDQ 节点
    OnnxExporter().export(file_path='exported.onnx', graph=quantized.copy())
    
    # 这个有
    ONNXRUNTIMExporter().export(file_path='exported.onnx', graph=quantized.copy())

**Comment by shuyuan-wang** [comment]
这个会报错貌似：
<img width="607" alt="image" src="https://user-images.githubusercontent.com/104115572/211263584-3f9cd2d1-1365-4f48-b5b7-6ae92148d3cd.png">
