### ISSUE TITLE
yolox量化

### ISSUE THREAD

**Issue by shuyuan-wang** [openppl-public/ppq#359]
我在尝试对yolox_s进行量化，主要是使用mscoco training dataset中每隔100个选一张图作为calibration dataset，使用ProgramEntrance.py.  修改了一下calibration_data_loader，写成了一个其他的dataloader，也使用了fine-tune，但是出来的onnx和tensorrt engine都跑飞了，能否帮忙看一下是什么问题？

附件为我使用的onnx和Program engine，pull的应该是“更新TensorRT部署的例子”这个commit为最后一个commit。

链接为我使用的文件和onnx
链接: https://pan.baidu.com/s/1FNmA_WXz4785BFf_-XZY_A?pwd=er2v 提取码: er2v

**Comment by ZhangZhiPku** [comment]
容我来检查一下

**Comment by shuyuan-wang** [comment]
量化效果是不是和batch_size有关，越大越好？

**Comment by ZhangZhiPku** [comment]
好像不是
