### ISSUE TITLE
resize节点TQC dominator互相引用递归报错

### ISSUE THREAD

**Issue by lzx1413** [openppl-public/ppq#369]
示例模型
```python
from torch import nn 
import torch.nn.functional as F
import torch
class ToyModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, stride=2, padding=1)
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, stride=2, padding=1)
    
    def forward(self, x):
        x0 = self.conv1(x)
        x1 = self.conv2(x0)
        x2 = F.interpolate(x1, scale_factor=2, mode='bilinear', align_corners=True)
        x3 = x0+x2
        return x3

model = ToyModel()
model.cpu().eval()
input_shape = (1, 1, 128, 128)
one_img = torch.randn(input_shape)
dynamic_axes = None
mode = torch.onnx.TrainingMode.EVAL
output_file = 'toymodel.onnx'
torch.onnx.export(
    model,
    one_img,
    output_file,
    training=mode,
    export_params=True,
    do_constant_folding=True,
    opset_version=11,
    input_names=['input'],
    output_names=['output'],
    )
```

**Comment by ZhangZhiPku** [comment]
出现上述问题的原因似乎是这样的：
在 ppq.core.common.py 中有定义

```python
# PASSIVE OPERATIONS 是那些不参与计算的 Op, 这些 op 的输入与输出将直接共享 scale
# 同时这些 op 前后的定点过程将被直接停用
PASSIVE_OPERATIONS = {
    'Resize', 'MaxPool', 'GlobalMaxPool', 'Reshape', 'Flatten', 'Identity', 'Dropout'
    'Slice', 'Pad', 'Split', 'Transpose', 'Interp', 'Squeeze', 'Unsqueeze'}
```

但在 ppq.optim.refine.QuantAlignmentPass 中会再次对 Resize 的输入和输出进行处理，这两次的处理刚好相反。

在 PASSIVE_OPERATIONS 定义的算子将输出向输入对齐。

在 ppq.optim.refine.QuantAlignmentPass 定义的内容将算子的输出向输入对齐，从而产生了上述问题。

因此可以简单地将 Resize 算子从 PASSIVE_OPERATIONS 中移除即可...

**Comment by lzx1413** [comment]
修改之后，还有个报错
```
Traceback (most recent call last):
  File "/home/zx_li/workspace/ppq/ppq/executor/torch.py", line 532, in __forward
    inputs = operation_runtime_hook.pre_forward_hook(inputs=inputs)
  File "/home/zx_li/workspace/ppq/ppq/quantization/analyse/graphwise.py", line 49, in pre_forward_hook
    self.i_storage[idx].append(tensor_random_fetch(
  File "/home/zx_li/workspace/ppq/ppq/utils/fetch.py", line 45, in tensor_random_fetch
    assert num_of_elements > 0, ('Can not fetch data from tensor with less than 1 elements.')
AssertionError: Can not fetch data from tensor with less than 1 elements.
```
好像resize节点这块还是有个空的tensor作为了输出

**Comment by ZhangZhiPku** [comment]
后面这个问题就很奇怪了，这是ppq自己的代码给你报的错误，graphwise_error_analyse需要抓取算子的输出从而对比结果的相似度，但是你好像有个算子的输出是空的，而且你能跑到这一步说明前面的量化都跑完了，是调用graphwise_error_analyse时送入的数据错了？

**Comment by NrealLzx** [comment]
Resize_forward()里如果参数values没有设置size而是设置scale_factor, size会被设置为None, 然后graphwise_error_analyse处理的时候这个size作为input就报错了吧

**Comment by lzx1413** [comment]
Resize_forward()里如果参数values没有设置size而是设置scale_factor, size会被设置为None, 然后graphwise_error_analyse处理的时候这个size作为input就报错了吧

**Comment by ZhangZhiPku** [comment]
graphwise_error_analyse好像不管input只管output的，而且好像只管conv, gemm这些的output，你可以在它的代码中看到这些逻辑，所以我会很奇怪你为啥能执行到这个错误上。

**Comment by lzx1413** [comment]
resize在DSP quantizer里也是在quant_operation_types里，然后如果从 PASSIVE_OPERATIONS 移除的话就会在torch exector里统计input output的量化反量化信息了

**Comment by ZhangZhiPku** [comment]
啥？我可是在graphwise_error_analyse里面写了额外的限制的：
```python
interested_op = [operation for operation in graph.operations.values()
                 if (isinstance(operation, QuantableOperation) and operation.is_computing_op)]
```

这可是要 computing_op 的(Gemm, Conv, Lstm, Attention, MatMul)

**Comment by ZhangZhiPku** [comment]
resize的定点逻辑错误问题将在这个 #375 补丁中修复

**Comment by NrealLzx** [comment]
> 后面这个问题就很奇怪了，这是ppq自己的代码给你报的错误，graphwise_error_analyse需要抓取算子的输出从而对比结果的相似度，但是你好像有个算子的输出是空的，而且你能跑到这一步说明前面的量化都跑完了，是调用graphwise_error_analyse时送入的数据错了？

这个错误是报在statistical_analyse里了， 那里面对interested_opr的限制比较宽松

**Comment by lzx1413** [comment]
> graphwise_error_analyse好像不管input只管output的，而且好像只管conv, gemm这些的output，你可以在它的代码中看到这些逻辑，所以我会很奇怪你为啥能执行到这个错误上。

这个错误是报在statistical_analyse里了， 那里面对interested_opr的限制比较宽松 😂

**Comment by ZhangZhiPku** [comment]
莫要慌张，这个问题将不定期修复
