### ISSUE TITLE
如何导出QDQ Onnx(Tensorrt使用)？

### ISSUE THREAD

**Issue by Noobzm** [openppl-public/ppq#374]
请问如何导出QDQ Onnx(Tensorrt使用)呢？使用export_ppq_graph()，默认是导出普通的onnx+量化参数，并不会调用TensorRTExporter_QDQ是吗？如果不传入config_save_to参数好像会报错，麻烦大佬解答一下疑惑哈

**Comment by ZhangZhiPku** [comment]
好像你需要这个？
https://github.com/openppl-public/ppq/blob/master/ppq/samples/TensorRT/Example_PTQ.py

**Comment by Noobzm** [comment]
我使用了这个example, 生成的是普通的onnx＋json+wts，并没有带量化信息的QDQ onnx，是我哪里理解有错吗？

**Comment by Noobzm** [comment]
> 好像你需要这个？ https://github.com/openppl-public/ppq/blob/master/ppq/samples/TensorRT/Example_PTQ.py

我理解的QDQ ONNX 应该是带有量化解量化信息的onnx，可以直接被tensorrt8解析，是这样的吗？

**Comment by ZhangZhiPku** [comment]
QDQ Onnx 太灵活了，总体感觉不是特别好用，如果你使用 TensorRT 的话，可以使用这个 onnx+json 的方式导出文件。
然后生成 engine 也就直接使用那个 build_engine 函数就行。

如果你要生成带 QDQ 节点的 onnx，选择导出平台为 ONNXRUNTIME 即可。

**Comment by Noobzm** [comment]
好的，明白了，感谢志佬解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(周四) 下午5:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [openppl-public/ppq] 如何导出QDQ Onnx(Tensorrt使用)？ (Issue #374)




 
QDQ Onnx 太灵活了，总体感觉不是特别好用，如果你使用 TensorRT 的话，可以使用这个 onnx+json 的方式导出文件。
 然后生成 engine 也就直接使用那个 build_engine 函数就行。
 
如果你要生成带 QDQ 节点的 onnx，选择导出平台为 ONNXRUNTIME 即可。

**Comment by Garfield2005** [comment]
@ZhangZhiPku,  导出带QDQ的Onnx时，权重部分直接导出为int8类型了，能否支持weight也是包含QDQ格式的？
