### ISSUE TITLE
scale_candidates选择问题

### ISSUE THREAD

**Issue by BobxmuMa** [openppl-public/ppq#383]
您好！
您在FP8量化的observer里定义scale的候选参数为：
`scale_candidates = [.0078125, .03125, .125, 1.0, 4.0, 16.0, 64.0]`

为什么scale的候选参数都是2的指数形式？是因为在浮点量化函数`QuantizeScalarFloating`中要保持所有的操作都是位操作吗。

另外您说：浮点量化对scale并不敏感。您有没有做过除了上面scale候选参数之外的scale值对精度影响的实验，比如不是2的指数形式的scale值。

**Comment by ZhangZhiPku** [comment]
在推理框架中进行浮点量化时，大概率会选用power-of-2的策略，因此Scale只能是2的整数次幂。
在部分INT8量化的推理框架中（主要是端侧框架），我们也会使用power-of-2策略，使用该策略实现的量化框架将具有更高的执行效率与更低的编程难度。

在PPQ中，我们实现的 QuantizeScalarFloating 函数可以执行任意 scale 的量化，不论他是否是 power-of-2 的，事实上它连非对称的浮点量化也可以算。

如你所见，PPQ 的 FP8 量化与 graphcore 公司合作研发，已经在硬件上完成测试，因此GraphcoreFP8Quantizer细节策略都是照着graphcore的硬件做的，而 TensorRT 目前尚未支持FP8的推理，但大概率也会采用power-of-2策略。我并不建议你研究scale对他的影响，这是由于推理实现上非2的指数的scale会产生额外计算开销，而且FP8对scale并不敏感。

关于scale对精度影响的实验，最具说服力的是你可以初始化一个高斯分布的样本总体，使用fp8量化并观察它的量化误差随scale的变化情况。此处我们使用的scale是由0.001逐渐扩大的，并没有遵顼power-of-2的约束，结果显示FP8的量化不吃scale这一套。

https://zhuanlan.zhihu.com/p/574825662

**Comment by BobxmuMa** [comment]
> 在推理框架中进行浮点量化时，大概率会选用power-of-2的策略，因此Scale只能是2的整数次幂。 在部分INT8量化的推理框架中（主要是端侧框架），我们也会使用power-of-2策略，使用该策略实现的量化框架将具有更高的执行效率与更低的编程难度。
> 
> 在PPQ中，我们实现的 QuantizeScalarFloating 函数可以执行任意 scale 的量化，不论他是否是 power-of-2 的，事实上它连非对称的浮点量化也可以算。
> 
> 如你所见，PPQ 的 FP8 量化与 graphcore 公司合作研发，已经在硬件上完成测试，因此GraphcoreFP8Quantizer细节策略都是照着graphcore的硬件做的，而 TensorRT 目前尚未支持FP8的推理，但大概率也会采用power-of-2策略。我并不建议你研究scale对他的影响，这是由于推理实现上非2的指数的scale会产生额外计算开销，而且FP8对scale并不敏感。
> 
> 关于scale对精度影响的实验，最具说服力的是你可以初始化一个高斯分布的样本总体，使用fp8量化并观察它的量化误差随scale的变化情况。此处我们使用的scale是由0.001逐渐扩大的，并没有遵顼power-of-2的约束，结果显示FP8的量化不吃scale这一套。
> 
> https://zhuanlan.zhihu.com/p/574825662

好的好的，十分感谢！
