### ISSUE TITLE
ProgramEntrance_2.py

### ISSUE THREAD

**Issue by shuyuan-wang** [openppl-public/ppq#389]
如果onnx的input是dynamic shape, 

```
executor.tracing_operation_meta(inputs=torch.zeros(size=args.shape).cuda())
```

这里的shape怎么放阿，是dynamic的那一个轴写-1吗？还有什么其它地方需要改来适配dynamic shape吗？

**Comment by ZhangZhiPku** [comment]
你不能在此处配置dynamic shape。

在PPQ中我们不关心这个模型是不是dynamic shape的，只有推理引擎关心这个事情。
在执行完executor.tracing_operation_meta(inputs=torch.zeros(size=args.shape).cuda())之后，你可以任意修改图中variable的形状。

使用下面的语句，你可以任意修改图中variable的尺寸信息：
```python
graph.variables['Variable Name'].shape = ['Batchsize', 1, 2, 3]
graph.variables['Variable Name'].shape = [100, -1, 2, 3]
graph.variables['Variable Name'].shape = [3, 1, 2, 3]
```
