### ISSUE TITLE
在PFL.Pipeline中加入LearnedStepSizePass和ParameterBakingPass后FP16的engine AP变低了

### ISSUE THREAD

**Issue by shuyuan-wang** [openppl-public/ppq#390]
如题，这个是因为baking吗？

**Comment by ZhangZhiPku** [comment]
可能是的，这两个pass都要改变权重的值，它们不会关心fp16的模型精度

**Comment by shuyuan-wang** [comment]
但是我加了这俩后，int8比没有加的时候还低了，这个是为啥

**Comment by ZhangZhiPku** [comment]
运气问题吧...

**Comment by shuyuan-wang** [comment]
志佬，我量化centerpoint的后半段用finetune和baking以后做evaluate会比只做ptq差，我是不是有什么设置错了？这次是之比较了int8，不finetune比finetune最后结果差

**Comment by ZhangZhiPku** [comment]
记得调参...
