### ISSUE TITLE
理论最大值疑惑

### ISSUE THREAD

**Issue by BobxmuMa** [openppl-public/ppq#398]
![image](https://user-images.githubusercontent.com/71216044/222696103-bdd583af-0c7b-4b8e-8a3b-cba5d3101ec6.png)

按照您的描述，当FP8 E4M3的指数与底数全取1时，达到无穷大。那么FP8 E4M3的理论最大值不应该是0 1111 110=+448吗。但是您代码里认为理论最大值为0 1111 111=+480. 这时E4M3不应该取无穷大吗。这点困惑我没有搞明白，希望您能解答一下，万分感谢！

![image](https://user-images.githubusercontent.com/71216044/222696621-43eb4c48-9b83-4fb5-8560-4905529d65aa.png)

**Comment by ZhangZhiPku** [comment]
这个你需要看一眼nvidia的那篇论文，他们没有使用0 1111 111表示无穷大。
