### ISSUE TITLE
 项目中一些模型例子的模型去哪下载么？，想复现一下

### ISSUE THREAD

**Issue by cqray1990** [openppl-public/ppq#399]

**Comment by ZhangZhiPku** [comment]
预计下周我们会公开一个大型模型库，包含图像分类，分割，检测，ocr，超分辨率，姿态检测等多项任务，并包含相应的数据。

**Comment by ZhangZhiPku** [comment]
您可以查看这个 https://github.com/openppl-public/ppq/tree/master/ppq/samples/QuantZoo
