### ISSUE TITLE
statistical_analyse报错

### ISSUE THREAD

**Issue by LHH20000923** [openppl-public/ppq#401]
当我使用statistical_analyse时，在上采样节点即onnx的resize处会报错。
![sendpix1](https://user-images.githubusercontent.com/83012544/223066332-99b1acfe-959e-4057-95cb-6b4608a71308.jpg)

![sendpix0](https://user-images.githubusercontent.com/83012544/223066161-a38ba7f4-e99e-48a3-805c-7dc99ebdd458.jpg)

请问我应该如何修改？

**Comment by ZhangZhiPku** [comment]
您的问题似乎与之前兄弟的问题类似 #369 

您可以进入 statistical_analyse 这个函数的定义中，其位于
https://github.com/openppl-public/ppq/blob/master/ppq/quantization/analyse/graphwise.py#L186

在该文件的第298行中，为其添加更严格的限制，或者移除resize类型的监听：

``` python
    for operation in graph.operations.values():
        if operation.type == 'Resize': continue # add this
        if isinstance(operation, QuantableOperation) and operation.type not in PASSIVE_OPERATIONS:
            interested_op.append(operation)
```
