### ISSUE TITLE
使用AdaroundPass优化，精度反而下降

### ISSUE THREAD

**Issue by LHH20000923** [openppl-public/ppq#402]
按照原论文Adaround不是优于四舍五入吗？但根据优化后的layer_wise来看，网络每一层独立量化误差SNR相比没优化的反而增大了。

**Comment by ZhangZhiPku** [comment]
Adaround pass好像被塞进legacy里面了，很久没有人关心他了，作为替代品你可以试试 learned step size optimization

**Comment by LHH20000923** [comment]
原论文没有开源，我查看了ppq中adaround的实现和mqbench中adaround的实现基本是一致的。不知道您所说的不同是在哪呢？

**Comment by ZhangZhiPku** [comment]
您可以尝试在这个最新的模型库中调试算法的性能：https://github.com/openppl-public/ppq/tree/master/ppq/samples/QuantZoo。
您可以自行实现一个 AdaRound Pass 与 ppq 中集成的  learned step size optimization 方法进行对比。在 8-bit 量化的情况下，ppq 中的算法应该具有更高的性能。

**Comment by LHH20000923** [comment]
Quantzoo中目标检测的网盘无法查看

**Comment by ZhangZhiPku** [comment]
额，那个老说有文件违规，我也不知道咋回事
