### ISSUE TITLE
量化yolov7问题

### ISSUE THREAD

**Issue by stezpy** [openppl-public/ppq#405]
yolov7-x量化过程中遇到了问题，代码如下

使用的ppq版本 0.6.5.1

注意用的input shape是 16x3x416x416，使用的yolov7模型是官方版本，export时使用动态batch，尺寸batchx3x416x416

执行
python3 quantize_models.py yolov7x.onnx --batch_size 16

    import argparse
    import os
    import shutil
    from typing import Iterable
    
    import onnx
    import torch
    from ppq import BaseGraph, QuantizationSettingFactory, TargetPlatform
    from ppq.api import export_ppq_graph, quantize_onnx_model
    from torch.utils.data import DataLoader
    
    
    
    def parse_args():
        parser = argparse.ArgumentParser("Quantize onnx graph weights")
        parser.add_argument("model_path", help="onnx filepath")
        parser.add_argument("--save-dir", default=".", help="directory to save output")
        parser.add_argument(
            "--input_shape", type=list, default=[3, 416, 416], help="input shape of model"
        )
        parser.add_argument("--batch_size", type=int, default=1, help="batch size")
        return parser.parse_args()
    
    
    def save_quantized_model(model_path, dst_dir, input_shape, batch_size):
        model_name = os.path.basename(model_path).split(".")[0]
        if os.path.exists(dst_dir):
            shutil.rmtree(dst_dir)
            os.makedirs(dst_dir)
        else:
            os.makedirs(dst_dir)
        DEVICE = "cuda"  # only cuda is fully tested :(  For other executing device there might be bugs.
        PLATFORM = (
            TargetPlatform.PPL_CUDA_INT8
        ) 
    
        def load_calibration_dataset() -> Iterable:
            return [torch.rand(size=input_shape) for _ in range(32)]
    
        def collate_fn(batch: torch.Tensor) -> torch.Tensor:
            return batch.to(DEVICE)
    
        quant_setting = QuantizationSettingFactory.pplcuda_setting()
    
        # Load training data for creating a calibration dataloader.
        calibration_dataset = load_calibration_dataset()
        calibration_dataloader = DataLoader(
            dataset=calibration_dataset, batch_size=batch_size, shuffle=True
        )
        # quantize your model.
        quantized = quantize_onnx_model(
            onnx_import_file=model_path,
            calib_dataloader=calibration_dataloader,
            calib_steps=32,
            input_shape=[batch_size] + input_shape,
            setting=quant_setting,
            collate_fn=collate_fn,
            platform=PLATFORM,
            device=DEVICE,
            verbose=0,
        )
    
        # Quantization Result is a PPQ BaseGraph instance.
        assert isinstance(quantized, BaseGraph)
    
        quant_model_name = os.path.join(dst_dir, "quantized_" + model_name)
        # export quantized graph.
        export_ppq_graph(
            graph=quantized,
            platform=PLATFORM,
            graph_save_to=quant_model_name + ".onnx",
            config_save_to=os.path.join(dst_dir, "quantized_" + model_name) + ".json",
        )
    
        quant_model_shape_name = quant_model_name + "_shape.onnx"
        onnx_model = onnx.load(quant_model_name + ".onnx")
        onnx.save(onnx.shape_inference.infer_shapes(onnx_model), quant_model_shape_name)
    
    
    if __name__ == "__main__":
        config = parse_args()
        model_path = config.model_path
        dst_dir = os.path.join(config.save_dir, "quant")
        input_shape, batch_size = config.input_shape, config.batch_size
        save_quantized_model(model_path, dst_dir, input_shape, batch_size)

具体报错如下

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/ppq/executor/torch.py", line 371, in __forward
        outputs = operation_forward_func(operation, inputs, self._executing_context)
      File "/usr/local/lib/python3.7/site-packages/ppq/executor/op/torch/default.py", line 787, in Concat_forward
        ASSERT_ALL_TENSORS_AT_SAME_DEVICE(op=op, values=values)
      File "/usr/local/lib/python3.7/site-packages/ppq/executor/op/torch/base.py", line 109, in ASSERT_ALL_TENSORS_AT_SAME_DEVICE
        raise ValueError(f'Input tensors do not share a same device. ({[d for d in devices]})')
    ValueError: Input tensors do not share a same device. (['cuda', 'cpu'])
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "quantize_models.py", line 100, in <module>
        save_quantized_model(model_path, dst_dir, input_shape, batch_size)
      File "quantize_models.py", line 75, in save_quantized_model
        verbose=0,
      File "/usr/local/lib/python3.7/site-packages/ppq/core/defs.py", line 54, in _wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/ppq/api/interface.py", line 290, in quantize_onnx_model
        collate_fn=collate_fn
      File "/usr/local/lib/python3.7/site-packages/ppq/core/defs.py", line 54, in _wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/ppq/quantization/quantizer/base.py", line 57, in quantize
        executor.tracing_operation_meta(inputs=inputs)
      File "/usr/local/corex-3.1.0.20230227.458/lib64/python3/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/ppq/core/defs.py", line 54, in _wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/ppq/executor/torch.py", line 437, in tracing_operation_meta
        hooks=hooks)
      File "/usr/local/lib/python3.7/site-packages/ppq/executor/torch.py", line 398, in __forward
        raise RuntimeError(f'Error happens when dealing with operation {str(operation)}')
    RuntimeError: Error happens when dealing with operation Concat_479(TargetPlatform.FP32) - inputs:['776_3', '727'], outputs:['734']

**Comment by ZhangZhiPku** [comment]
看起来你只需要更新就可以
