### ISSUE TITLE
Question: why adding 0.25 when left idx == right idx?

### ISSUE THREAD

**Issue by HYLcool** [openppl-public/ppq#406]
Hi, I found that in TorchMSEObserver, when idx is in the range of (start, end) and the distance to the left/right edges of the corresponding quantized bin, the error is the distance plus 0.25. Why it's 0.25 instead of 0.5?
https://github.com/openppl-public/ppq/blob/e0298ad2721aa84e027420f615714ec525d3b632/ppq/quantization/observer/range.py#L447

**Comment by ZhangZhiPku** [comment]
忘了...但那段代码我验算过...
