### ISSUE TITLE
拷贝graph时报错

### ISSUE THREAD

**Issue by LHH20000923** [openppl-public/ppq#407]
![1](https://user-images.githubusercontent.com/83012544/224526283-9c1884a0-5052-4041-acf6-32328c2e001b.png)
使用深拷贝时会出现如下错误，不知道如何修改。
![2](https://user-images.githubusercontent.com/83012544/224526303-75cb3b9d-2c7e-44c2-aea6-c5ab5eca8f5e.png)

**Comment by LHH20000923** [comment]
好像是中间的输入输出节点并没有数值，所以拷贝会报错

**Comment by ZhangZhiPku** [comment]
问题已经收到，我会在下一次更新中修复上述问题
