### ISSUE TITLE
statistical_analyse分析，有些操作的输入是整型，会导致统计时torch.mean()错误

### ISSUE THREAD

**Issue by EliLei** [openppl-public/ppq#409]
感谢大佬开发ppq这么强大的量化库。发现一个小小问题

ppq 0.6.6  torch 1.10
ppq/quantization/analyse/graphwise.py , line 362

statistical_analyse 分析 Slice 操作时，有data、starts、ends、axes、steps五个输入，后面四个都是整数。在统计时，record['Quantized Input']和record['Dequantized Input']都是int64。在StatisticalErrorAnalyser.stat()里面会取torch.mean()，报错
RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

**Comment by ZhangZhiPku** [comment]
啊对，经常有人报告这个问题...
#401
