### ISSUE TITLE
做Calibration的时候很慢

### ISSUE THREAD

**Issue by tuochi** [openppl-public/ppq#410]
Calibration Progress(Phase 1):   1%|          | 5/500 [01:06<1:58:59, 14.42s/it]

配置信息：
batch_size=16
EXECUTING_DEVICE = 'cuda:0'
QUANT_PLATFROM = TargetPlatform.TRT_INT8
QS.lsq_optimization_setting.collecting_device = 'cuda:0'  # 缓存数据放在那，cuda 就是放在gpu，如果显存超了你就换成 'cpu'

显卡信息
|   1  Tesla T4            Off  | 00000000:5E:00.0 Off |                    0 |
| N/A   65C    P0    49W /  70W |   2596MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |

**Comment by ZhangZhiPku** [comment]
没开那个 ENABLE_CUDA_KERNEL 吧...

**Comment by tuochi** [comment]
是的，感谢~
