### ISSUE TITLE
我在训练集上做calibration，用验证集做误差分析，结果Graphwise Quantization Error差距非常大

### ISSUE THREAD

**Issue by tuochi** [openppl-public/ppq#411]
Layer     | NOISE:SIGNAL POWER RATIO 
Conv_3:   | ████████████████████ | 2.035911
Conv_146: | ████████████████     | 1.757310
Conv_252: | ███████████████      | 1.661766
Conv_249: | ███████████████      | 1.655996
Conv_132: | ███████████████      | 1.655069
Conv_64:  | ███████████████      | 1.654916
Conv_142: | ███████████████      | 1.650048
Conv_264: | ███████████████      | 1.641752
Conv_119: | ███████████████      | 1.640494
Conv_23:  | ███████████████      | 1.638234
Conv_261: | ███████████████      | 1.623788
Conv_255: | ███████████████      | 1.621127
Conv_258: | ███████████████      | 1.615906
Conv_150: | ██████████████       | 1.605970
Conv_245: | ██████████████       | 1.590330
Conv_115: | ██████████████       | 1.583901
Conv_238: | ██████████████       | 1.579520
Conv_219: | ██████████████       | 1.573021
Conv_268: | ██████████████       | 1.572567
Conv_223: | ██████████████       | 1.551087
Conv_226: | ██████████████       | 1.546806
Conv_235: | █████████████        | 1.531307
Conv_77:  | █████████████        | 1.526408
Conv_108: | █████████████        | 1.520111
Conv_126: | █████████████        | 1.463823
Conv_60:  | █████████████        | 1.463512
Conv_139: | █████████████        | 1.460287
Conv_36:  | ████████████         | 1.444025
Conv_135: | ████████████         | 1.432896
Conv_229: | ████████████         | 1.426118
Conv_188: | ████████████         | 1.422361
Conv_16:  | ████████████         | 1.397544
Conv_53:  | ████████████         | 1.394711
Conv_153: | ███████████          | 1.377728
Conv_242: | ███████████          | 1.369191
Conv_84:  | ███████████          | 1.364243
Conv_101: | ███████████          | 1.357077
Conv_27:  | ███████████          | 1.341254
Conv_71:  | ███████████          | 1.338686
Conv_232: | ███████████          | 1.330824
Conv_9:   | ███████████          | 1.328445
Conv_184: | ███████████          | 1.325853
Conv_212: | ███████████          | 1.322132
Conv_216: | ███████████          | 1.311350
Conv_80:  | ███████████          | 1.307097
Conv_178: | ██████████           | 1.302697
Conv_172: | ██████████           | 1.283150
Conv_91:  | ██████████           | 1.275754
Conv_181: | ██████████           | 1.272876
Conv_191: | ██████████           | 1.272710
Conv_94:  | █████████            | 1.198683
Conv_175: | █████████            | 1.182298
Conv_160: | █████████            | 1.175868
Conv_12:  | █████████            | 1.172804
Conv_19:  | █████████            | 1.170548
Conv_0:   | █████████            | 1.151654
Conv_74:  | ████████             | 1.143648
Conv_209: | ████████             | 1.137146
Conv_30:  | ████████             | 1.126644
Conv_87:  | ████████             | 1.108222
Conv_105: | ████████             | 1.088035
Conv_98:  | ████████             | 1.082261
Conv_46:  | ███████              | 1.063117
Conv_163: | ███████              | 1.049416
Conv_43:  | ███████              | 1.038634
Conv_6:   | ███████              | 1.030918
Conv_169: | ██████               | 0.975922
Conv_50:  | ██████               | 0.962346
Conv_39:  | ██████               | 0.960472
Conv_57:  | ██████               | 0.957010
Conv_129: | █████                | 0.913800
Conv_68:  | █████                | 0.855325
Conv_123: | ████                 | 0.824769
Conv_203: | ████                 | 0.810520
Conv_206: | ███                  | 0.764117
Conv_112: | ███                  | 0.756854
Conv_200: | ███                  | 0.745971
Conv_33:  | ███                  | 0.696468
Conv_197: |                      | 0.496492

用的是yolov5m，如果我只用calibration的图片来计算误差的话倒是很正常。

**Comment by tuochi** [comment]
用的是yolov5m，如果我只用calibration的图片来计算误差的话倒是很正常。

**Comment by ZhangZhiPku** [comment]
数据集开shuffle了？

**Comment by tuochi** [comment]
是的，开了shuffle，不开shuffle如下结果。这个误差会偏大吗？

Layer     | NOISE:SIGNAL POWER RATIO 
Conv_64:  | ████████████████████ | 0.047400
Conv_261: | █████████████████    | 0.041102
Conv_235: | █████████████████    | 0.040606
Conv_268: | ████████████████     | 0.039203
Conv_242: | ████████████████     | 0.037606
Conv_219: | ███████████████      | 0.035355
Conv_245: | ██████████████       | 0.033469
Conv_232: | ██████████████       | 0.033062
Conv_238: | ██████████████       | 0.032881
Conv_258: | █████████████        | 0.032240
Conv_216: | █████████████        | 0.031829
Conv_36:  | █████████████        | 0.030998
Conv_226: | ████████████         | 0.029370
Conv_16:  | ████████████         | 0.029086
Conv_19:  | ████████████         | 0.028734
Conv_229: | ████████████         | 0.028674
Conv_60:  | ████████████         | 0.028302
Conv_223: | ████████████         | 0.028000
Conv_252: | ███████████          | 0.027202
Conv_12:  | ███████████          | 0.026629
Conv_53:  | ███████████          | 0.025648
Conv_264: | ██████████           | 0.025433
Conv_27:  | ██████████           | 0.024627
Conv_43:  | ██████████           | 0.024516
Conv_212: | ██████████           | 0.023761
Conv_255: | ██████████           | 0.023749
Conv_115: | ██████████           | 0.023455
Conv_249: | █████████            | 0.023150
Conv_191: | █████████            | 0.022438
Conv_209: | █████████            | 0.022334
Conv_181: | █████████            | 0.021747
Conv_178: | █████████            | 0.021612
Conv_119: | █████████            | 0.021505
Conv_30:  | █████████            | 0.021354
Conv_188: | ████████             | 0.020747
Conv_146: | ████████             | 0.020005
Conv_132: | ████████             | 0.019742
Conv_46:  | ████████             | 0.019660
Conv_71:  | ███████              | 0.017936
Conv_39:  | ███████              | 0.017673
Conv_50:  | ███████              | 0.017531
Conv_172: | ███████              | 0.017182
Conv_108: | ███████              | 0.017140
Conv_57:  | ███████              | 0.016688
Conv_175: | ███████              | 0.016419
Conv_139: | ██████               | 0.016223
Conv_153: | ██████               | 0.016096
Conv_150: | ██████               | 0.015874
Conv_142: | ██████               | 0.015324
Conv_84:  | ██████               | 0.015128
Conv_101: | ██████               | 0.014758
Conv_77:  | ██████               | 0.014533
Conv_68:  | ██████               | 0.014375
Conv_184: | █████                | 0.013945
Conv_91:  | █████                | 0.013865
Conv_206: | █████                | 0.013572
Conv_203: | █████                | 0.013308
Conv_74:  | █████                | 0.013303
Conv_33:  | █████                | 0.012922
Conv_9:   | █████                | 0.012634
Conv_126: | █████                | 0.012600
Conv_94:  | █████                | 0.012507
Conv_105: | █████                | 0.012435
Conv_98:  | ████                 | 0.011607
Conv_135: | ████                 | 0.011385
Conv_200: | ████                 | 0.011356
Conv_87:  | ████                 | 0.011008
Conv_160: | ████                 | 0.010491
Conv_169: | ████                 | 0.010477
Conv_163: | ████                 | 0.009882
Conv_123: | ████                 | 0.009854
Conv_129: | ████                 | 0.009540
Conv_112: | ███                  | 0.009108
Conv_80:  | ███                  | 0.008632
Conv_197: | ███                  | 0.008272
Conv_23:  | ███                  | 0.007474
Conv_3:   | █                    | 0.004076
Conv_6:   | █                    | 0.002529
Conv_0:   |                      | 0.001278

**Comment by ZhangZhiPku** [comment]
这个应该没啥问题

**Comment by tuochi** [comment]
好的，感谢。
