### ISSUE TITLE
int8模型的输出和fp32模型的输出置信度偏差蛮大的

### ISSUE THREAD

**Issue by tuochi** [openppl-public/ppq#413]
模型: yolov5mv6.0 
数据集:coco
我量化后用int8的onnx和fp32模型发现置信度有的偏差比较多。请问能做到int8模型在置信度上只相差0.01级别的差距吗？如果可以的话，请问应该要怎么做呢？感谢~~

torch output:{'result': [[[62, [153, 1, 341, 111], 0.88299], [57, [221, 341, 417, 592], 0.79555], [58, [223, 205, 300, 259], 0.74694], [58, [270, 307, 306, 329], 0.69744], [58, [269, 259, 312, 301], **0.67782**]]]}
onnx output:{'result': [[[62, [153, 0, 341, 111], 0.87496], [57, [221, 341, 416, 592], 0.79299], [58, [222, 205, 310, 260], 0.71678], [58, [271, 307, 306, 329], 0.66383], [58, [269, 260, 313, 301], **0.60559**]]]}
torch output:{'result': [[[0, [21, 14, 359, 638], **0.61876**]]]}
onnx output:{'result': [[[0, [20, 15, 359, 636], **0.58866**]]]}
torch output:{'result': [[[6, [133, 2, 365, 598], 0.9212]]]}
onnx output:{'result': [[[6, [133, 4, 366, 598], 0.90755]]]}

**Comment by tuochi** [comment]
你好，我更新到最新版了，相比**0.6**版本的偏差，这个版本好了特别多。想请问一下，同样的配置，这个版本做了什么优化呢？

```
torch output:{'result': [[[62, [153, 1, 341, 111], 0.88299], [57, [221, 341, 417, 592], 0.79555], [58, [223, 205, 300, 259], 0.74694], [58, [270, 307, 306, 329], 0.69744], [58, [269, 259, 312, 301], **0.67782**]]]}
onnx output:{'result': [[[62, [153, 1, 341, 111], 0.88334], [57, [220, 341, 417, 592], 0.78984], [58, [223, 205, 300, 259], 0.74705], [58, [270, 307, 306, 329], 0.69108], [58, [269, 259, 312, 301], **0.67779**]]]}
torch output:{'result': [[[0, [21, 14, 359, 638], **0.61876**]]]}
onnx output:{'result': [[[0, [20, 11, 360, 640], **0.60739**]]]}
torch output:{'result': [[[6, [133, 2, 365, 598], 0.9212]]]}
onnx output:{'result': [[[6, [133, 2, 366, 597], 0.91786]]]}
```

**Comment by ZhangZhiPku** [comment]
啥...你是咋测的置信度

**Comment by tuochi** [comment]
> 哦...应该没啥优化，好像只是导出逻辑换了换？

昨天检查错了，新版tensorRT导出的onnx只是原本的计算图，所以好了特别多的原因应该是这个。置信度差别还是很大

**Comment by ZhangZhiPku** [comment]
你的置信度结果大概0.6-0.9左右，如果你要求误差在0.01以内，误差能量相比信号能量只占0.027%

这个量级的误差难以实现，int8的误差比这个大100倍，大概在1%~3%之间。

**Comment by tuochi** [comment]
我发现ppq 0.66的时候尽管我卷积选择的策略是perchannal，但是看了**TensorRTUtil.py**以后发现是对每个tensor设定为abs(value)和 -abs(value)，现在在tensorRT平台上是取消了perchannel的部署方式吗？如果不是的话我应该怎么导出perchannel的量化设定？0.6版本的导出的QDQ Onnx是能看到perchannel。还有就是下面我跑TRT_int8的信噪比，这个信噪比是不是偏高了？感谢~~~~

Layer     | NOISE:SIGNAL POWER RATIO 
Conv_191: | ████████████████████ | 43.026%
Conv_115: | ███████████████████  | 40.048%
Conv_219: | ██████████████████   | 38.137%
Conv_108: | █████████████████    | 37.115%
Conv_101: | █████████████████    | 36.791%
Conv_238: | ████████████████     | 34.420%
Conv_268: | ███████████████      | 31.852%
Conv_119: | ██████████████       | 31.221%
Conv_245: | ██████████████       | 30.997%
Conv_60:  | ██████████████       | 30.772%
Conv_235: | ██████████████       | 30.537%
Conv_181: | ██████████████       | 30.200%
Conv_261: | ██████████████       | 30.053%
Conv_53:  | ██████████████       | 29.820%
Conv_188: | ██████████████       | 29.509%
Conv_223: | ██████████████       | 29.413%
Conv_178: | █████████████        | 28.134%
Conv_226: | █████████████        | 28.067%
Conv_212: | █████████████        | 27.948%
Conv_229: | █████████████        | 27.768%
Conv_232: | █████████████        | 27.438%
Conv_216: | █████████████        | 27.228%
Conv_264: | █████████████        | 27.131%
Conv_242: | ████████████         | 26.567%
Conv_252: | ████████████         | 26.240%
Conv_153: | ████████████         | 25.937%
Conv_258: | ████████████         | 25.345%
Conv_94:  | ████████████         | 24.812%
Conv_146: | ███████████          | 24.789%
Conv_249: | ███████████          | 24.532%
Conv_139: | ███████████          | 24.405%
Conv_142: | ███████████          | 24.224%
Conv_255: | ███████████          | 24.204%
Conv_132: | ███████████          | 23.553%
Conv_105: | ███████████          | 23.551%
Conv_209: | ██████████           | 22.494%
Conv_98:  | ██████████           | 21.921%
Conv_175: | ██████████           | 21.903%
Conv_91:  | ██████████           | 21.567%
Conv_84:  | ██████████           | 21.365%
Conv_150: | ██████████           | 20.953%
Conv_172: | ██████████           | 20.873%
Conv_77:  | ██████████           | 20.703%
Conv_126: | ██████████           | 20.612%
Conv_135: | █████████            | 20.302%
Conv_57:  | █████████            | 20.234%
Conv_43:  | █████████            | 20.089%
Conv_87:  | █████████            | 19.902%
Conv_71:  | █████████            | 19.590%
Conv_184: | █████████            | 19.264%
Conv_64:  | █████████            | 19.180%
Conv_39:  | ████████             | 18.182%
Conv_50:  | ████████             | 17.824%
Conv_129: | ████████             | 17.281%
Conv_74:  | ████████             | 17.248%
Conv_46:  | ████████             | 17.126%
Conv_112: | ████████             | 16.338%
Conv_160: | ███████              | 15.174%
Conv_36:  | ███████              | 14.988%
Conv_123: | ███████              | 14.911%
Conv_163: | ███████              | 14.521%
Conv_169: | ███████              | 14.375%
Conv_80:  | ██████               | 13.388%
Conv_12:  | ██████               | 13.096%
Conv_68:  | ██████               | 12.389%
Conv_203: | ██████               | 12.262%
Conv_206: | ██████               | 12.089%
Conv_200: | █████                | 11.254%
Conv_19:  | █████                | 10.498%
Conv_16:  | █████                | 10.153%
Conv_27:  | ████                 | 9.628%
Conv_30:  | ████                 | 9.292%
Conv_9:   | ████                 | 8.646%
Conv_197: | ████                 | 8.597%
Conv_33:  | ███                  | 6.292%
Conv_23:  | ██                   | 3.538%
Conv_6:   | █                    | 1.429%
Conv_3:   | █                    | 1.324%
Conv_273: |                      | 1.123%
Conv_271: |                      | 0.928%
Conv_272: |                      | 0.729%
Conv_0:   |                      | 0.122%

**Comment by tuochi** [comment]
> 你的置信度结果大概0.6-0.9左右，如果你要求误差在0.01以内，误差能量相比信号能量只占0.027%
> 
> 这个量级的误差难以实现，int8的误差比这个大100倍，大概在1%~3%之间。

我导出openvino的onnx文件也是发现，虽然conv选的是perchannel但是相关的PPQ Variance 只有一个值

**Comment by ZhangZhiPku** [comment]
是不是写错了...

**Comment by ZhangZhiPku** [comment]
好像tensorrt只需要设置activation的scale，不需要设置weight的scale。

**Comment by tuochi** [comment]
> 好像tensorrt只需要设置activation的scale，不需要设置weight的scale（weight会自动按min-max方式计算scale，并以perchannel方式部署）。

那这样之前的QDQ方式是不是比较好点，部署的时候能和量化得出来得结果对齐？还有openvino的perchannel呢？

**Comment by ZhangZhiPku** [comment]
这两种方法各有优劣，你都可以试试。
不过Openvino应该是可以弄出perchannel的参数的，https://github.com/openppl-public/ppq/blob/master/ppq/quantization/quantizer/OpenvinoQuantizer.py#L43
