### ISSUE TITLE
graphwise_error_analyse 分析出现很大的误差

### ISSUE THREAD

**Issue by uniquezhengjie** [openppl-public/ppq#416]
使用mobilenetv2模型，比如运行ppq/samples/Tutorial/calibration.py会出现很大的误差值：
<img width="750" alt="image" src="https://user-images.githubusercontent.com/30591323/228794876-40b5ccab-b63d-46a7-906c-27da0e135ad5.png">

calibration的数据如果直接读取原始jpg或者png图片需要怎么预处理？，我使用torchvision transforms 或者原始值以及其他处理方式，量化mobilenetv2都会有10%+的误差。

**Comment by Jzz24** [comment]
标定数据集采用与模型测试集一致的预处理就行。mobilenet v2的

**Comment by uniquezhengjie** [comment]
标定预处理我使用：torchvision.models.MobileNet_V2_Weights.IMAGENET1K_V1.transforms()  这个我已经使用pytorch推理验证过没问题。
我使用的platform是TargetPlatform.TRT_INT8，采用的是per-channel量化，但是graphwise_error_analyse还是会有10%+的误差：
<img width="701" alt="image" src="https://user-images.githubusercontent.com/30591323/229063720-11b647e0-f1db-4e7d-86ad-3c018a5e18b3.png">
另外你说的"其relu6激活函数，还无法进行weight变换"具体说什么意思？

**Comment by ZhangZhiPku** [comment]
这个mobilenet v2误差就是挺高的，量化出来的分类准确率还行，你可以参考这个结果：
https://github.com/openppl-public/ppq/tree/master/ppq/samples/QuantZoo

**Comment by uniquezhengjie** [comment]
谢谢解答，使用graphwise_error_analyse分析最后一层的误差一般在多少以内认为是合适的呢

**Comment by ZhangZhiPku** [comment]
你要是图像分类，那个一般10%的误差都没啥大事。
你要是图像超分，那就0.1%

**Comment by uniquezhengjie** [comment]
Done

**Comment by uniquezhengjie** [comment]
closed
