### ISSUE TITLE
after qutantize en_PP-OCRv3_rec_infer.onnx acc is lower as the image table show

### ISSUE THREAD

**Issue by cqray1990** [openppl-public/ppq#419]
FP acc is 67.36 Quant acc is is only 40.64 , that is the quant model can't be used

**Comment by ZhangZhiPku** [comment]
那他就是用不了啊...

**Comment by cqray1990** [comment]
> 那他就是用不了啊...

对于文字识别的量化效果是不是都不怎么好？还是我操作哪里不对？

**Comment by ZhangZhiPku** [comment]
paddle ocr的那一批模型都是轻量化的模型，都不好量化。对一些误差不算特别高的网络你可以开启lsq算法训练一下，这样的效果应该差不多，其他的基本就告别量化了。
