### ISSUE TITLE
PPL_CUDA_INT8只支持per_channel的量化方式 吗

### ISSUE THREAD

**Issue by SSriven** [openppl-public/ppq#421]
如何设置per_tensor的量化方式

**Comment by ZhangZhiPku** [comment]
ppl cuda 推理框架只支持 per_channel 的量化方式，但 ppq 可以模拟 per_tensor 的量化，你只需要将 ppq/quantization/quantizer/PPLCUDAQuantizer 中的逻辑改为 per_tensor 即可。

**Comment by SSriven** [comment]
修改之后会报Can not assign QuantizationProperty.PER_TENSOR policy to a Channel-wise Tensor Quantization Config instance.
报错的地方在ppq/quantization/quantizer/PPLCUDAQuantizer 中的第43行ChannelwiseTensorQuantizationConfig处，我试着去找了下有没有TensorwiseTensorQuantizationConfig这个类，然而没有找到。如果我使用ppl_cuda_int8平台去量化，是不是只能是per_channel，如果强行将ppq/quantization/quantizer/PPLCUDAQuantizer 中的逻辑改为 per_tensor也是不行的。

**Comment by SSriven** [comment]
报错解决了，将ChannelwiseTensorQuantizationConfig中的报错语句删除即可，但是输出的json文件中看不太懂是啥意思，我想拿到每一层卷积的scale和每一层激活的scale，这个该怎么获取
