### ISSUE TITLE
ONNXRUNTIMExporter 导出的 QDQ ONNX 如何去除 ReLU 和 Clip 算子

### ISSUE THREAD

**Issue by Goose-Bomb** [openppl-public/ppq#427]
ORT 的量化工具导出的 QDQ 格式 ONNX 中会自动折叠所有的 ReLU/Clip 算子，如下图：

<img width="601" alt="图片" src="https://user-images.githubusercontent.com/24779939/231226479-c75fa7a3-a160-41f5-9fc9-55d9beb9bbc4.png">

但是 PPQ v0.6.6 的 `ONNXRUNTIMExporter` 导出的 QDQ 格式 ONNX 仍然保留了 ReLU/Clip 算子：

<img width="636" alt="图片" src="https://user-images.githubusercontent.com/24779939/231226728-7273f315-704e-426b-a8ae-e04113e7ced9.png">

我看了下 `ONNXRUNTIMExporter` 的源码应该是有折叠这些激活函数算子的逻辑的，不知道为何没有工作，请问该如何设置才能和 ORT 量化工具的导出行为一致呢？

**Comment by ZhangZhiPku** [comment]
好像确实有这段代码...让我看看咋回事

**Comment by ZhangZhiPku** [comment]
问题将在最新的更新中被修复： https://github.com/openppl-public/ppq/pull/429
