### ISSUE TITLE
QuantZoo里面的sr量化设置合理吗

### ISSUE THREAD

**Issue by pixel-lt** [openppl-public/ppq#428]
Hi，大佬，我看MyInt8Quantizer在init_quantize_config函数里面量化算子的output的state设置成fp32，同时类似于Add，concat之类的算子并没有纳入到量化的范围，这种处理方式似乎并非全量化，更像是一种混合精度计算吧

**Comment by ZhangZhiPku** [comment]
是的，MyInt8Quantizer并不是能够完成部署的量化器，他只是用来测试理论精度的

**Comment by pixel-lt** [comment]
那如果我想要将整网以16bit计算，是否只需要把BIT_WIDTH设置成16, 同时将各个算子的output state保持默认设置就ok了？

**Comment by ZhangZhiPku** [comment]
你好像还需要重新设置quant min, quant max

**Comment by zt706** [comment]
> 

那如果 MyInt8Quantizer 这个量化器需要 能够部署，需要怎么修改呢？
