### ISSUE TITLE
分布差异较大的数据，制作校准集时的注意事项有什么？

### ISSUE THREAD

**Issue by zhjw0927** [openppl-public/ppq#463]
一个模型的训练数据包括白天和夜晚的图像，在制作校准集时，是不是也需要涵盖白天和夜晚的数据？
比如使用单一白天的数据，量化效果会有差异吗？
还是建议分开使用白天和夜晚的数据制作两个校准集，得到白天和夜晚下的两个量化模型？
请帮帮我，谢谢！

**Comment by ZhangZhiPku** [comment]
两者均可，模型量化就好像拿calibration数据集重新训练一下模型，所以如果你单独拿白天的数据量化，那他应该是不行...

**Comment by zhjw0927** [comment]
> 你说的方法两者均可，模型量化就好像拿calibration数据集重新训练一下模型，所以如果你单独拿白天的数据量化，那他应该是不行...

好的，明白了，谢谢！
