### ISSUE TITLE
ONNX如何在ARM架构的NVIDIA计算平台上生成engine？

### ISSUE THREAD

**Issue by zhjw0927** [openppl-public/ppq#465]
大佬好：
使用PPQ定制化了量化方式，并证明量化方法是可行的。如何在ARM架构的板子上生成engine呢？
如果repo中提供了指导方法，请谅解我提出这个问题。
因为PPQ对于量化学习是非常有帮助的，后续我肯定投入其中并且推荐。但对于业务生产的目的，想直接了解下使用PPQ进行方法调研，之后进行部署的可行性？
希望大佬给出指导，谢谢！

**Comment by zhjw0927** [comment]
再补充一个问题，从源码安装好像不是以developer模式安装吧，修改源文件，运行不生效呢？

**Comment by zhjw0927** [comment]
好的，谢谢指导

**Comment by zhjw0927** [comment]
大佬好，我再请教个问题。请问能提供下PPQ生成量化模型的onnx和json文件的code示例吗？或者相关的参数设置呢？

**Comment by ZhangZhiPku** [comment]
你好像需要这个？
https://github.com/openppl-public/ppq/tree/master/ppq/samples/TensorRT

**Comment by lDarryll** [comment]
> 你好像需要这个？ https://github.com/openppl-public/ppq/tree/master/ppq/samples/TensorRT

作者你好，这个生成engine的 lenet_int8.cpp，好像是通过下图的方式利用tensorrt c++ 的api一步一步搭建的engine，是否有利用c++ trt.OnnxParser的方式进行构建的例子
<img width="1009" alt="111" src="https://github.com/openppl-public/ppq/assets/34019070/0a3a098d-3d6d-4448-856c-b366d150a843">
