### ISSUE TITLE
训练后的模型使用训练集作为标定的graphwise_error 大于 随机初始化的数据

### ISSUE THREAD

**Issue by zhjw0927** [openppl-public/ppq#467]
志佬好：

自定义训练集包含白天和夜晚两种分布，yolov5m模型在此基础上进行训练。针对标定数据集的使用，分别进行了四次实验，具体如下：
1. 标定：640张纯白天图像，                               snr_report：7.095%
2. 标定：640张纯夜晚图像，                               snr_report：7.658%
3. 标定：640张白天夜晚混合图像，                    snr_report：7.386%
4. 标定：640张随机初始化数据（torch.rand），snr_report：3.556%

可以确定四个实验下的图像预处理是一致的，并且与yolov5m模型的训练是一致的，即：
mode: RGB
shape: (3,640,640)
dtype: float32
range: 0-1

这种情况是正常的吗？有什么建议吗？

**Comment by ZhangZhiPku** [comment]
是正常的，你不能使用随机数据完成量化，他没有意义

**Comment by zhjw0927** [comment]
好的，感谢解答！
