### ISSUE TITLE
校准时报shape不匹配的错误

### ISSUE THREAD

**Issue by ehuaa** [openppl-public/ppq#468]
大佬好，我根据官方的export脚本生成了一个yolov3的torchscript的模型，然后使用以下代码试图跑02_Quantization.py中的示例，其实就是代码中onnx替换成了torchscript， 然后报了以下的错误 
![1684159972648](https://github.com/openppl-public/ppq/assets/5137359/7fab1ec3-a63c-406f-9940-de155ef7cdc3)
原始运行的代码如下所示：
![1684160509904](https://github.com/openppl-public/ppq/assets/5137359/cdf068e3-36c3-468f-b6de-25d48d8b5a19)

**Comment by ehuaa** [comment]
试了一下batchsize=1的时候才能正确生成，想问下如何修改代码才能让batchsize=32也可以成功输出量化模型呢

**Comment by ZhangZhiPku** [comment]
你的onnx模型里面写死了batchsize=1，对于reshape这样的算子而言，它会需要一个shape信息作为输入，在导出这个onnx时你可能将shape的第一维设置成了1，因此他不能在batchsize=32时执行这个reshape。你需要做的事情是在导出模型的时候协商dynamic_shape，或者以batchsize=32导出模型。

**Comment by ehuaa** [comment]
> 你的onnx模型里面写死了batchsize=1，对于reshape这样的算子而言，它会需要一个shape信息作为输入，在导出这个onnx时你可能将shape的第一维设置成了1，因此他不能在batchsize=32时执行这个reshape。你需要做的事情是在导出模型的时候协商dynamic_shape，或者以batchsize=32导出模型。

多谢大佬，解决了。。问题出在我的校准集不是32的倍数 然后没有drop_last导致最后一个batch shape不匹配
