### ISSUE TITLE
想问下只能对torchvision里面的model进行量化吗

### ISSUE THREAD

**Issue by lofyol** [openppl-public/ppq#471]

**Comment by ZhangZhiPku** [comment]
应该随便一个onnx都可以，你遇到了什么问题？

**Comment by lofyol** [comment]
> 应该随便一个onnx都可以，你遇到了什么问题？

还没遇到，只是想问下，就是随便一个torch的模型都可以进行量化嘛

**Comment by ZhangZhiPku** [comment]
差不多是的

**Comment by JinXiaozhao** [comment]
@ZhangZhiPku 能帮忙看下我的这个模型吗？
模型是从TensorFlow转换的onnx模型，模型输入为[-1,10,122]，校验集数据为[2008,10,122]；
请问如下参数是否正确，如错误请问应该填哪些？
INPUT_LAYOUT          = 'chw' 
NETWORK_INPUTSHAPE    = [1, 10, 122]
CALIBRATION_BATCHSIZE = 2088       

加载校验集数据函数，是否需要修改？
def load_calibration_dataset_usad():
    datas = np.load('/home/ppq/data.npy')
    res = [datas[i:i+1] for i in range(datas.shape[0])]
    return res
