### ISSUE TITLE
关于 LSTM 算子的量化支持与疑问

### ISSUE THREAD

**Issue by zwshan** [openppl-public/ppq#473]
志佬你好，我几乎看完了您在 B 站的教学视频，收获颇丰。我现在手里有一个 torch 导出的 onnx 模型，其中有 5 个 LSTM 层,并且我通过 Nsight system的套件进行了分析，这 5 个 LSTM 层是我应用的性能瓶颈。我翻遍的文档以及 issue 中有关的内容，发现似乎 ppq 可能不支持 LSTM 层的量化？我看到您在某个 issue 中提到，只有 trt 这个后端支持 lstm 的量化。
请问如果我想让 ppq 支持 LSTM 的量化，我的学习路径或者工程路线大概应该是什么呢？
是否需要涉及到写一个 LSTM 层拆解的代码？（拆解成简单的 Gemm算子和激活函数等）
以及如果我想要实现 INT4和 INT8 的混合精度量化或者 INT8 和 FP16 的混合精度量化，这是可行的吗？如果可行大佬可以给我一些提示吗？我也想为 PPQ 这个社区做一些贡献。

**Comment by ZhangZhiPku** [comment]
tensorrt量化lstm时应该是动态量化的，并不需要给出量化参数
ppq里面也支持动态量化这种方案，但没有任何 quantizer 里面写了这个策略，没有任何 quantizer 会尝试去量化 lstm。
所谓动态量化，是指网络的输入在运行过程中动态地统计最大/最小值从而确定scale，这一过程会消耗额外的时间，大多是情况下都不会带来性能收益。
LSTM与大语言模型类似，都是自回归结构，如果采取静态量化的方式，其精度会受到较为严重的影响，这一问题目前仍然是难以解决的。
