### ISSUE TITLE
有关openvino量化

### ISSUE THREAD

**Issue by HIT-Wang** [openppl-public/ppq#480]
您好，感谢您团队优秀的工作，给了我很大的帮助。
我目前量化了一个openvino的real-esrgan超分模型，首先加入了quant_modules.initialize()做了量化训练，后面又用您的脚本把onnx做了量化（[脚本](https://github.com/openppl-public/ppq/blob/master/ppq/samples/Openvino/Example_PTQ.py)）。但是目前超分效果相比没做量化以前图片会变暗。请问有什么策略或者方法可以让量化后的模型保持精度吗？我应该怎么操作？SAMPLE那里我用如下代码做了替换：

```
def data_pre(img_dir):
    data_list = []
    for image_path in os.listdir(img_dir):
        img = Image.open(osp.join(img_dir, image_path))
        img = np.array(img)
        img = np.squeeze(img)
        img = img / 255.
        img = img.transpose((2, 0, 1))
        img = np.expand_dims(img, axis=0)
        img = torch.tensor(img)
        img = img.type(torch.FloatTensor)
        data_list.append(img)
    return data_list
```

**Comment by ZhangZhiPku** [comment]
您可以使用这些策略来帮助提升超分模型的量化精度：
1. 手动将模型最后几个层解除量化
2. 调用一些算法来提升量化效果，例如 lsq optimization, bias correction...

**Comment by HIT-Wang** [comment]
> 您可以使用这些策略来帮助提升超分模型的量化精度：
> 
> 1. 手动将模型最后几个层解除量化
> 2. 调用一些算法来提升量化效果，例如 lsq optimization, bias correction...

您好，请问在ppq框架中，有相关策略的使用文档吗？

**Comment by ZhangZhiPku** [comment]
啊？quant_modules.initialize()好像是torch fx的用法，您可能指的是您已经在网络训练的过程中进行了qat，但您需要注意以下问题：
1. 超分模型对误差极其敏感，根本容忍不了很大的量化误差，训练过程就像是买彩票，中奖概率不大。
2. 使用 torch fx 或者 ppq 等各种工具进行 qat，您需要注意这些框架与最终执行的openvino是存在对齐误差的，您的网路量化最后要承受对齐误差和量化误差双方面的影响。
3. 图片变暗的原因可能与 calibration method 相关，目前 ppq 默认使用 percentile 方法对激活值进行校准，这将使得输出的表示范围被压缩，注意到颜色[255, 255, 255]为纯白，经过量化后的网络很可能输出不了这个值，它最大的表示范围可能被压缩到更小。您可以将最后几层的校准方式调整为minmax(请参考program entrance 2中的用法)，或者直接将最后几层解除量化。

您最好直接解除部分层的量化，这个方案比 qat 稳得多，而且检测、超分模型最后几层上int8必定掉精度。这是因为int8量化只能表示256个有效数字，其中正数部分只有127个数，您的颜色分布是从[0, 255]的，共计256个颜色需要表示，这意味着网络输出时，如果您执行对称量化必定有一半颜色表示不了。怎么 qat 都没用。

**Comment by HIT-Wang** [comment]
> 啊？quant_modules.initialize()好像是torch fx的用法，您可能指的是您已经在网络训练的过程中进行了qat，但您需要注意以下问题：
> 
> 1. 超分模型对误差极其敏感，根本容忍不了很大的量化误差，训练过程就像是买彩票，中奖概率不大。
> 2. 使用 torch fx 或者 ppq 等各种工具进行 qat，您需要注意这些框架与最终执行的openvino是存在对齐误差的，您的网路量化最后要承受对齐误差和量化误差双方面的影响。
> 3. 图片变暗的原因可能与 calibration method 相关，目前 ppq 默认使用 percentile 方法对激活值进行校准，这将使得输出的表示范围被压缩，注意到颜色[255, 255, 255]为纯白，经过量化后的网络很可能输出不了这个值，它最大的表示范围可能被压缩到更小。您可以将最后几层的校准方式调整为minmax(请参考program entrance 2中的用法)，或者直接将最后几层解除量化。
> 
> 您最好直接解除部分层的量化，这个方案比 qat 稳得多，而且检测、超分模型最后几层上int8必定掉精度。这是因为int8量化只能表示256个有效数字，其中正数部分只有127个数，您的颜色分布是从[0, 255]的，共计256个颜色需要表示，这意味着网络输出时，如果您执行对称量化必定有一半颜色表示不了。怎么 qat 都没用。

您好，感谢回复～我去尝试一下，另外想问您一个问题：您有提到超分模型对误差极其敏感，从广义的角度来讲（不只限于超分模型），ppq框架中有提供什么策略或者方法去针对这些敏感模型吗？

**Comment by HIT-Wang** [comment]
> 检测框回归，超分辨率，自回归模型(RNN, LLM, Stable Diffusion)这些任务都对误差极其敏感，他们都不太好量化。 在遇到量化问题时，您可以采取以下策略对误差进行分析：
> 
> 1. 您将利用 ppq 中提供的误差分析函数: graphwise_error_analyse, layerwise_error_analyse, statistical_analyse对网络量化情况进行详细分析；他们会帮助您定位问题。
> 2. 在 graphwise_error_analyse 分析中，如果您发现您的网络误差并非是随着层数增多而线性扩大的，而是非线性指数级扩大的，您就可以跑路了——这样的网络没人能量化，我说的，耶稣也留不住他。
> 3. 在 layerwise_error_analyse 分析中，您可以发现那些层的量化对网络精度影响最大，您可以考虑解除他们的量化。
> 4. 在 statistical_analyse 分析中，ppq 会详细导出每一层的激活于权重的分布情况，您可以观察网络权重是否分布的很奇怪，就好像许多论文中提到的网络存在异常值从而使得量化精度很差。但是您需要注意，异常值的出现跟网络量化精度没有什么必然的联系，我可以给你造一个没有任何异常值的网络但它就是不可能量化，我也可以给你造一个权重上万的网络量化的很不错——关于数值分布与量化误差之间的关系您需要进行更加深入而理性的分析。
> 5. 您将使用 ppq 中提供的优化过程去解决网络量化误差过大的问题，ppq 目前提供的优化过程包括 lsq optimization, bias correction, channel split, layerwise equalization等等，其中我需要向您额外推荐 lsq optimization 与 layerwise equalization。他们是网络量化万金油，ppq 对他们的实现非常的猛，您可以尝试调整他们的参数从而降低量化误差。
> 6. 您将调整校准方法与校准数据集来提升量化精度，由于 ppq cuda kernel 的实现，ppq可以以百倍的性能完成模型的 calibration，您可以逐层、逐 tensor 的调整校准算法从而提升网络精度，并且他们测试起来非常快。

感谢您详细的回复，我去调用这些方法深入分析一下网络，salute！🫡

**Comment by HIT-Wang** [comment]
> 检测框回归，超分辨率，自回归模型(RNN, LLM, Stable Diffusion)这些任务都对误差极其敏感，他们都不太好量化。 在遇到量化问题时，您可以采取以下策略对误差进行分析：
> 
> 1. 您将利用 ppq 中提供的误差分析函数: graphwise_error_analyse, layerwise_error_analyse, statistical_analyse对网络量化情况进行详细分析；他们会帮助您定位问题。
> 2. 在 graphwise_error_analyse 分析中，如果您发现您的网络误差并非是随着层数增多而线性扩大的，而是非线性指数级扩大的，您就可以跑路了——这样的网络没人能量化，我说的，耶稣也留不住他。
> 3. 在 layerwise_error_analyse 分析中，您可以发现那些层的量化对网络精度影响最大，您可以考虑解除他们的量化。
> 4. 在 statistical_analyse 分析中，ppq 会详细导出每一层的激活于权重的分布情况，您可以观察网络权重是否分布的很奇怪，就好像许多论文中提到的网络存在异常值从而使得量化精度很差。但是您需要注意，异常值的出现跟网络量化精度没有什么必然的联系，我可以给你造一个没有任何异常值的网络但它就是不可能量化，我也可以给你造一个权重上万的网络量化的很不错——关于数值分布与量化误差之间的关系您需要进行更加深入而理性的分析。
> 5. 您将使用 ppq 中提供的优化过程去解决网络量化误差过大的问题，ppq 目前提供的优化过程包括 lsq optimization, bias correction, channel split, layerwise equalization等等，其中我需要向您额外推荐 lsq optimization 与 layerwise equalization。他们是网络量化万金油，ppq 对他们的实现非常的猛，您可以尝试调整他们的参数从而降低量化误差。
> 6. 您将调整校准方法与校准数据集来提升量化精度，由于 ppq cuda kernel 的实现，ppq可以以百倍的性能完成模型的 calibration，您可以逐层、逐 tensor 的调整校准算法从而提升网络精度，并且他们测试起来非常快。

您好，得再打扰一下您，想再请教您一个问题，我将超分模型尝试从onnx转trt的时候，发现比从onnx转openvino的误差要大很多，请问ppq框架里有针对trt的优化方法不？或者阿伟那里怎么说（不是，开个玩笑

**Comment by HIT-Wang** [comment]
> > 检测框回归，超分辨率，自回归模型(RNN, LLM, Stable Diffusion)这些任务都对误差极其敏感，他们都不太好量化。 在遇到量化问题时，您可以采取以下策略对误差进行分析：
> > 
> > 1. 您将利用 ppq 中提供的误差分析函数: graphwise_error_analyse, layerwise_error_analyse, statistical_analyse对网络量化情况进行详细分析；他们会帮助您定位问题。
> > 2. 在 graphwise_error_analyse 分析中，如果您发现您的网络误差并非是随着层数增多而线性扩大的，而是非线性指数级扩大的，您就可以跑路了——这样的网络没人能量化，我说的，耶稣也留不住他。
> > 3. 在 layerwise_error_analyse 分析中，您可以发现那些层的量化对网络精度影响最大，您可以考虑解除他们的量化。
> > 4. 在 statistical_analyse 分析中，ppq 会详细导出每一层的激活于权重的分布情况，您可以观察网络权重是否分布的很奇怪，就好像许多论文中提到的网络存在异常值从而使得量化精度很差。但是您需要注意，异常值的出现跟网络量化精度没有什么必然的联系，我可以给你造一个没有任何异常值的网络但它就是不可能量化，我也可以给你造一个权重上万的网络量化的很不错——关于数值分布与量化误差之间的关系您需要进行更加深入而理性的分析。
> > 5. 您将使用 ppq 中提供的优化过程去解决网络量化误差过大的问题，ppq 目前提供的优化过程包括 lsq optimization, bias correction, channel split, layerwise equalization等等，其中我需要向您额外推荐 lsq optimization 与 layerwise equalization。他们是网络量化万金油，ppq 对他们的实现非常的猛，您可以尝试调整他们的参数从而降低量化误差。
> > 6. 您将调整校准方法与校准数据集来提升量化精度，由于 ppq cuda kernel 的实现，ppq可以以百倍的性能完成模型的 calibration，您可以逐层、逐 tensor 的调整校准算法从而提升网络精度，并且他们测试起来非常快。
> 
> 您好，得再打扰一下您，想再请教您一个问题，我将超分模型尝试从onnx转trt的时候，发现比从onnx转openvino的误差要大很多，请问ppq框架里有针对trt的优化方法不？或者阿伟那里怎么说（开个玩笑，哈哈哈

转trt的话，我用的是这个[脚本](https://github.com/openppl-public/ppq/blob/201d31cc0d04061f9e26347cd5e65d9d0522db96/ppq/utils/TensorRTUtil.py#L221)

**Comment by sanbuphy** [comment]
你好，我也在量化超分模型，我发现很大的精度损失，想请问你是怎么解决这个问题的？谢谢

**Comment by HIT-Wang** [comment]
> 你好，我也在量化超分模型，我发现很大的精度损失，想请问你是怎么解决这个问题的？谢谢

你是量化openvino还是量化trt？

**Comment by sanbuphy** [comment]
> > 你好，我也在量化超分模型，我发现很大的精度损失，想请问你是怎么解决这个问题的？谢谢
> 
> 你是量化openvino还是量化trt？

我量化trt，但我想其实意思是等价的，就是我想要把偏差过多的层回退到fp32

**Comment by HIT-Wang** [comment]
> 

貌似不太等价，具尝试，trt超分用ppq更难量化，偏移比openvino要大，也许是我方法不太对，不过总的来说，无论openvino还是trt，都没有找到合适的效果ok的量化方法，不过看上面作者的介绍，这个东西跟模型也有关系，也许可以尝试一下改一改模型结构再量化

**Comment by HIT-Wang** [comment]
> > > 你好，我也在量化超分模型，我发现很大的精度损失，想请问你是怎么解决这个问题的？谢谢
> > 
> > 
> > 你是量化openvino还是量化trt？
> 
> 我量化trt，但我想其实意思是等价的，就是我想要把偏差过多的层回退到fp32

貌似不太等价，具尝试，trt超分用ppq更难量化，偏移比openvino要大，也许是我方法不太对，不过总的来说，无论openvino还是trt，都没有找到合适的效果ok的量化方法，不过看上面作者的介绍，这个东西跟模型也有关系，也许可以尝试一下改一改模型结构再量化

**Comment by sanbuphy** [comment]
> > > > 你好，我也在量化超分模型，我发现很大的精度损失，想请问你是怎么解决这个问题的？谢谢
> > > 
> > > 
> > > 你是量化openvino还是量化trt？
> > 
> > 
> > 我量化trt，但我想其实意思是等价的，就是我想要把偏差过多的层回退到fp32
> 
> 貌似不太等价，具尝试，trt超分用ppq更难量化，偏移比openvino要大，也许是我方法不太对，不过总的来说，无论openvino还是trt，都没有找到合适的效果ok的量化方法，不过看上面作者的介绍，这个东西跟模型也有关系，也许可以尝试一下改一改模型结构再量化

好的，谢谢。是的 我感觉超分模型本身不太适合量化
