### ISSUE TITLE
> 你好像需要这个？ https://github.com/openppl-public/ppq/tree/master/ppq/samples/TensorRT

### ISSUE THREAD

**Issue by lDarryll** [openppl-public/ppq#483]
> 你好像需要这个？ https://github.com/openppl-public/ppq/tree/master/ppq/samples/TensorRT

作者你好，这个生成engine的 lenet_int8.cpp，好像是通过下图的方式利用tensorrt c++ 的api一步一步搭建的engine，是否有利用c++ trt.OnnxParser的方式进行构建的例子
<img width="1009" alt="111" src="https://github.com/openppl-public/ppq/assets/34019070/0a3a098d-3d6d-4448-856c-b366d150a843">

_Originally posted by @lDarryll in https://github.com/openppl-public/ppq/issues/465#issuecomment-1578985713_

**Comment by ZhangZhiPku** [comment]
并没有，但是你可以直接调ppq的工具函数，有个直接从python调tensorrt接口的，用过的都说好
https://github.com/openppl-public/ppq/blob/master/ppq/samples/TensorRT/Example_PTQ.py
