### ISSUE TITLE
请问dispatching_table是如何影响trt build_engine时各层precision的？

### ISSUE THREAD

**Issue by Nusselder9** [openppl-public/ppq#492]
我看到**best_practice.py**中有如下的设置：

`# 将前10个误差最大的层送上 FP32`
`for op_name, _ in sensitivity[: 10]:`
`    QS.dispatching_table.append(operation=op_name, platform=TargetPlatform.FP32)`

在这里设置后是否意味着针对tensorrt后端build_engine得到的engine，这10层是fp32的？我没有找到相关代码。

我在[TensorRTUtil.py](https://github.com/openppl-public/ppq/blob/95c34be4c13c18a4ec802f64815c9c8924489099/ppq/utils/TensorRTUtil.py#L214C8-L214C8)中发现**fp16**模式是默认开启的，（1）是不是意味着setDynamicRange(int8_scale_file)中没有scale的层是会被回退到fp16？（2）还是说是按照QS.dispatching_table 中的设置回退到fp32，但我没有找到相关代码。

可能是我看的不仔细没有看到，感谢答疑！

**Comment by ZhangZhiPku** [comment]
是的，当你使用了这个功能，PPQ会停止那几层的量化，这样输出的json文件里也不会有他们的量化信息。
如果你的engine启动了FP16，则解除量化的层将以FP16精度执行。
