### ISSUE TITLE
量化后模型导出为onnx时，强制在每个op前插入quantize/dequantize

### ISSUE THREAD

**Issue by SunCrazy** [openppl-public/ppq#499]
大佬 @ZhangZhiPku ，想请教一下，用ppq量化后的模型，如果选择导出平台为onnxruntime，怎么才能强制在每一个op的前面插入quantize/dequantize节点？我看有的时候reshape/transpose/concat+relu等这种不会插入量化节点。虽然从逻辑上讲确实也没必要插入，但是我们在实际项目中解析onnx的时候，对这种没有量化节点的op需要额外处理，相对麻烦一些。

所以想请教一下，ppq目前是否支持导出onnx模型时，强制让每个op前后都有量化节点？如果目前无法做到，我需要修改哪些内容能支持？非常感谢！

**Comment by ZhangZhiPku** [comment]
你可以使用 TQC(Tensor Quantization Config)上面的QuantizationVisibility属性

``` python
import torch

import ppq.lib as PFL
from ppq import TargetPlatform, TorchExecutor, graphwise_error_analyse, QuantableOperation, QuantizationVisibility
from ppq.api import ENABLE_CUDA_KERNEL, export_ppq_graph, load_onnx_graph, load_native_graph
from ppq.quantization.optim import *

# 你需要自己写一个函数来加载数据
calibration_dataloader = [
    {'input.1': torch.rand(size=[16,3,640,640]).cuda()}
    for _ in range(32)
]

with ENABLE_CUDA_KERNEL():
    graph = load_onnx_graph(onnx_import_file='Models/MyModel.onnx')
    # GraphFormatter(graph).truncate_on_var(var=graph.variables['Cut on me'], mark_as_output=True)

    quantizer   = PFL.Quantizer(platform=TargetPlatform.ONNXRUNTIME, graph=graph) # 取得 ONNXRUNTIME 所对应的量化器
    dispatching = PFL.Dispatcher(graph=graph).dispatch(                           # 生成调度表
        quant_types=quantizer.quant_operation_types)
    
    # 为算子初始化量化信息
    for op in graph.operations.values():
        quantizer.quantize_operation(
            op_name = op.name, platform = dispatching[op.name])

    # 初始化执行器
    collate_fn = None
    executor = TorchExecutor(graph=graph, device='cuda')
    executor.tracing_operation_meta(inputs={'input.1': torch.rand(size=[16,3,640,640]).cuda()})
    executor.load_graph(graph=graph)

    # 创建优化管线，在 ProgramEntrance_1.py 中，我们使用 QuantizationSetting 创建优化管线
    # 而在这里，所有的一切需要你手动创建
    pipeline = PFL.Pipeline([
        QuantizeSimplifyPass(),
        QuantizeFusionPass(
            activation_type=quantizer.activation_fusion_types),
        ParameterQuantizePass(),
        RuntimeCalibrationPass(),
        PassiveParameterQuantizePass(),
        QuantAlignmentPass(force_overlap=True),
    ])

    # 调用管线完成量化
    pipeline.optimize(
        graph=graph, dataloader=calibration_dataloader, verbose=True, 
        calib_steps=32, collate_fn=collate_fn, executor=executor)
    
    # 强制导出所有量化信息
    for op in graph.operations.values():
        if isinstance(op, QuantableOperation):
            for cfg, _ in op.config_with_variable:
                cfg.visibility = QuantizationVisibility.FORCE_EXPORT

    graphwise_error_analyse(
        graph=graph, running_device='cuda', dataloader=calibration_dataloader, 
        collate_fn=collate_fn)

    export_ppq_graph(
        graph=graph, platform=TargetPlatform.ONNXRUNTIME, 
        graph_save_to='Output/quantized.native', 
        config_save_to='Output/quantized.json')
```

**Comment by SunCrazy** [comment]
> 你可以使用 TQC(Tensor Quantization Config)上面的QuantizationVisibility属性
> 
> ```python
> import torch
> 
> import ppq.lib as PFL
> from ppq import TargetPlatform, TorchExecutor, graphwise_error_analyse, QuantableOperation, QuantizationVisibility
> from ppq.api import ENABLE_CUDA_KERNEL, export_ppq_graph, load_onnx_graph, load_native_graph
> from ppq.quantization.optim import *
> 
> # 你需要自己写一个函数来加载数据
> calibration_dataloader = [
>     {'input.1': torch.rand(size=[16,3,640,640]).cuda()}
>     for _ in range(32)
> ]
> 
> with ENABLE_CUDA_KERNEL():
>     graph = load_onnx_graph(onnx_import_file='Models/MyModel.onnx')
>     # GraphFormatter(graph).truncate_on_var(var=graph.variables['Cut on me'], mark_as_output=True)
> 
>     quantizer   = PFL.Quantizer(platform=TargetPlatform.ONNXRUNTIME, graph=graph) # 取得 ONNXRUNTIME 所对应的量化器
>     dispatching = PFL.Dispatcher(graph=graph).dispatch(                           # 生成调度表
>         quant_types=quantizer.quant_operation_types)
>     
>     # 为算子初始化量化信息
>     for op in graph.operations.values():
>         quantizer.quantize_operation(
>             op_name = op.name, platform = dispatching[op.name])
> 
>     # 初始化执行器
>     collate_fn = None
>     executor = TorchExecutor(graph=graph, device='cuda')
>     executor.tracing_operation_meta(inputs={'input.1': torch.rand(size=[16,3,640,640]).cuda()})
>     executor.load_graph(graph=graph)
> 
>     # 创建优化管线，在 ProgramEntrance_1.py 中，我们使用 QuantizationSetting 创建优化管线
>     # 而在这里，所有的一切需要你手动创建
>     pipeline = PFL.Pipeline([
>         QuantizeSimplifyPass(),
>         QuantizeFusionPass(
>             activation_type=quantizer.activation_fusion_types),
>         ParameterQuantizePass(),
>         RuntimeCalibrationPass(),
>         PassiveParameterQuantizePass(),
>         QuantAlignmentPass(force_overlap=True),
>     ])
> 
>     # 调用管线完成量化
>     pipeline.optimize(
>         graph=graph, dataloader=calibration_dataloader, verbose=True, 
>         calib_steps=32, collate_fn=collate_fn, executor=executor)
>     
>     # 强制导出所有量化信息
>     for op in graph.operations.values():
>         if isinstance(op, QuantableOperation):
>             for cfg, _ in op.config_with_variable:
>                 cfg.visibility = QuantizationVisibility.FORCE_EXPORT
> 
>     graphwise_error_analyse(
>         graph=graph, running_device='cuda', dataloader=calibration_dataloader, 
>         collate_fn=collate_fn)
> 
>     export_ppq_graph(
>         graph=graph, platform=TargetPlatform.ONNXRUNTIME, 
>         graph_save_to='Output/quantized.native', 
>         config_save_to='Output/quantized.json')
> ```

可以解决问题，感谢！
