### ISSUE TITLE
PPQ是否支持量化clip模型？

### ISSUE THREAD

**Issue by shhn1** [openppl-public/ppq#508]
求问大佬ppq是否支持量化clip模型或者vit模型？尝试对clip进行量化，流程上能跑通，误差分析那块结果飞了，完全不能用 T.T

**Comment by ZhangZhiPku** [comment]
这个即便你跑通也没法推理，不过我们后面会针对transformer提供更合理的解决方案，您可以关注我们的B站视频

**Comment by shhn1** [comment]
> 这个即便你跑通也没法推理，不过我们后面会针对transformer提供更合理的解决方案，您可以关注我们的B站视频

可以请问一下 没有办法推理的具体原因是什么嘛？

**Comment by ZhangZhiPku** [comment]
你可以加我的QQ: 281077761
