### ISSUE TITLE
请问为什么在运行 ppq/ppq/samples/TensorRT/Benchmark_with_onnx.py 文件时会出现Segmentation Fault的可能原因是什么？

### ISSUE THREAD

**Issue by wmWangmiao** [openppl-public/ppq#545]
运行ppq/ppq/samples/TensorRT/Benchmark_with_onnx.py 文件时会出现Segmentation Fault
报错信息定位在了第62行代码，可能的原因是什么？
<img width="452" alt="联想截图_20240323174204" src="https://github.com/openppl-public/ppq/assets/162577556/4205d560-7ca2-4ebd-ba89-bf95043115fd">

**Comment by ZhangZhiPku** [comment]
那谁知道啊
