### ISSUE TITLE
导出的QDQ ONNX模型转为TensorRT后，速度比FP16的ONNX还要慢？

### ISSUE THREAD

**Issue by zhishao** [openppl-public/ppq#575]
使用ProgramEntrance_1.py导出带qdq节点的onnx模型，速度比fp16的tensorrt模型还要慢是什么情况。

**Comment by zhishao** [comment]
导出tensorrt时使用的是https://github.com/OpenPPL/ppq/blob/master/md_doc/deploy_trt_by_api.md

**Comment by PhilipGAQ** [comment]
请问如何解决的
