### ISSUE TITLE
使用ONNXRUNTIME导出之后，推理报错INVALID_GRAPH

### ISSUE THREAD

**Issue by nostalgiaa-a** [openppl-public/ppq#583]
请问模型量化之后，onnxruntime推理报错是什么原因？
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./model_opset11.onnx failed:This is an invalid model. In Node, ("/Reshape", Reshape, "", -1) : ("onnx::Reshape_0": tensor(float),"/Constant_output_0": tensor(int64),) -> ("/Reshape_output_0": tensor(float),) , Error Unrecognized attribute: allowzero for operator Reshape 
之前看到有的issue说降opset版本到13，我降了以后还是有问题，怎么解决？

**Comment by nostalgiaa-a** [comment]
已解决，opset版本问题，onnx1.17和opset21可以正常推理

**Comment by jason666-md** [comment]
检查是否 self.EXPORT_PPQ_INTERNAL_INFO = False ，如果之前设置成True也会报错
