### ISSUE TITLE
BN是否可以单独被量化

### ISSUE THREAD

**Issue by Menace-Dragon** [openppl-public/ppq#61]
emmmm，又来叨扰你们勒。我在测试一个模型的时候，有这么个计算图：

...--->Add--->BN--->ReLU--->...

量化完成后，我查看了一下json文件，这个BN似乎没有被量化，想叨扰问下BN可以被量化吗，还是说模型不应该有这样单独存在的BN呢

**Comment by Jzz24** [comment]
bn是不支持量化的，推理后端也不支持bn的量化。模型设计中，尽量避免这种无法融合的bn

**Comment by Menace-Dragon** [comment]
好的，感谢
