### ISSUE TITLE
NotImplementError: Graph op LSTM has no backend implementation on target platform TargetPlatform.UNSPECIFIED

### ISSUE THREAD

**Issue by Menace-Dragon** [openppl-public/ppq#67]
emmmm，我又又来了...（不要嫌弃我hhh）有个NotImplementError，似乎是暂时还不支持LSTM算子吗？

**Comment by ZhangZhiPku** [comment]
这玩意你是怎么想到要去量化它的...只有tensorRT支持吧...

**Comment by Menace-Dragon** [comment]
呃呃，，，好吧...

**Comment by Menace-Dragon** [comment]
好的，明白勒，感谢😵

**Comment by ZhangZhiPku** [comment]
在即将发布的ppq 0.6.4版本中我们支持了gru的fp32执行，以及gru的算子拆解，你可以瞅一眼看看它的复杂程度...

**Comment by Menace-Dragon** [comment]
听着就很恐怖......近些天我也了解了LSTM内部实现，确实太复杂了，看得眼花
