### ISSUE TITLE
Upsample算子似乎不支持量化；ConTranpose似乎无法完成BN Fold；

### ISSUE THREAD

**Issue by Menace-Dragon** [openppl-public/ppq#69]
a. 在跑一个onnx测试模型时，报错Upsample算子 no bakend on target platform，似乎PPQ还不支持Upsample算子的量化，后续有可能会支持吗

b. 在跑另一个onnx测试模型时，模型中有这么个计算图：
     ...-->ConvTranspose-->BatchNrom-->ReLU-->...
     然后报错ConvTranspose算子无法和BN进行Fold

c. 还想叨扰请教一下，如果计算图为：
    ...-->BatchNrom-->Conv-->ReLU-->...
    那么可以进行Fold吗？

**Comment by ZhangZhiPku** [comment]
a. 听说这个算子从opset10开始后被onnx官方弃用了...
b. 这个问题好像之前群里有人也提过，我们正在添加这部分逻辑。
c. 请把这种bn插在conv前面的程序员抓来祭天，不过理论上这个是可以fold的。

**Comment by zhenglongjiepheonix** [comment]
@Menace-Dragon Upsample可以自己参照ppq/executor/op/torch/default.py里面的算子加个pytorch的实现，我们应该不会支持

**Comment by Menace-Dragon** [comment]
hahahaha好的，感谢感谢~

**Comment by ZhangZhiPku** [comment]
你可以用onnx版本转换工具把那个upsample干掉，它可能被resize之类的算子替换了
https://github.com/onnx/onnx/blob/main/docs/VersionConverter.md

**Comment by Menace-Dragon** [comment]
> 你可以用onnx版本转换工具把那个upsample干掉，它可能被resize之类的算子替换了 https://github.com/onnx/onnx/blob/main/docs/VersionConverter.md

确实是我的版本问题，我的onnx模型 opset=v9，确实需要版本转换。但是我今天也试过了这个version_converter，，报错了，估计是我的onnx模型不太符合version_converter的要求hhhhh，我再自己想办法解决了，再次感谢😞

**Comment by ZhangZhiPku** [comment]
Bn fold的问题已经在 #70 修正

**Comment by Menace-Dragon** [comment]
好勒！
