### ISSUE TITLE
'utf-8' codec can't decode byte 0xb4 in position 2833

### ISSUE THREAD

**Issue by Menace-Dragon** [openppl-public/ppq#85]
您好，我在我自己带GPU的电脑试了一下，发现在ppq\core\ffi.py第28行，报错这个'utf-8' codec can't decode byte 0xb4 in position 2833，调了半天一直无法解决，很郁闷，这是什么导致的呢

我用的是visual studio 2019

**Comment by Menace-Dragon** [comment]
oh，我解决了，吧visual studio 2019 的中文语言包卸载，装成纯英文语言包就行了...

**Comment by liuyuan000** [comment]
> oh，我解决了，吧visual studio 2019 的中文语言包卸载，装成纯英文语言包就行了...

请问怎么卸载
