### ISSUE TITLE
PPL_DSP_INT8量化后export问题

### ISSUE THREAD

**Issue by Menace-Dragon** [openppl-public/ppq#86]
GPU模式下，在跑RetinaFace（backbone为ResNet50时），量化过程成功跑完，在导出时报TypeError: Cannot convert Resize_133 to caffe op。debug发现是因为没有满足ppq/parser/caffe/caffe_export_utils.py 的第439行判断而导致的。

**Comment by Menace-Dragon** [comment]
哦，我懂了，看到utils.py实现细节了。应该是我导出的这个算子有问题

**Comment by Menace-Dragon** [comment]
![Capture](https://user-images.githubusercontent.com/58941349/166726752-590d0f39-41ba-476d-8c69-a60cf7bd53c8.PNG)
如图，（当然你也发现了，该resize算子输入尺寸为23x23，输出为45x45，居然不是2倍关系，我也迷惑

**Comment by Menace-Dragon** [comment]
但是我又看了一下，该模型是Pytorch.onnx export出来的opset11，应该是比较正常的算子，Resize算子写的虽然省略了东西但是应该没毛病（ONNXRuntime可以跑通该模型）

**Comment by ZhangZhiPku** [comment]
据我所知你拿ppq转换onnx的模型到caffe问题可多了，或者从caffe转换到onnx也一堆问题，主要是它们有些定义好像不是很一样...你确定要这样搞的话可以解除439行的判断试试，虽然它后面可能还要别的问题。

**Comment by Menace-Dragon** [comment]
有道理，emmmmmmmm那我暂时先不考虑这个模型了

**Comment by ZhangZhiPku** [comment]
好像就只有caffe进caffe出是可以的，你这个东西是输入了一个onnx然后要导出caffe？

**Comment by ZhangZhiPku** [comment]
好像不是这样的，这个PPL_DSP_INT8指的是按照PPL_DSP的量化规则对模型进行量化，确定每一个算子的具体量化细节。这一规则适用于PPL_DSP和SNPE平台。
